program dasagest;
uses crt;
var i,k:integer;
    c:char;
    source:text;
    att:array[1..50]of array[1..50] of shortint;
    attname:array[1..50]of string;
    name:array[1..50]of string;
    loc:array[1..50]of array[1..50]of integer;
    cursor:array[1..50]of integer;
    numrecs:array[1..50]of integer;
    data,atts:integer;
    percorso:string;

procedure title;
begin
gotoxy(1,1);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(2,1);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(3,1);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(4,1);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(5,1);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(6,1);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(7,1);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(8,1);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(38,1);
textbackground(6);
textcolor(0);
write(' ');
gotoxy(39,1);
textbackground(6);
textcolor(0);
write(' ');
gotoxy(52,1);
textbackground(1);
textcolor(0);
write(' ');
gotoxy(53,1);
textbackground(1);
textcolor(0);
write(' ');
gotoxy(72,1);
textbackground(0);
textcolor(7);
write('_');
gotoxy(1,2);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(2,2);
write(' ');
gotoxy(3,2);
write(' ');
gotoxy(4,2);
write(' ');
gotoxy(5,2);
write(' ');
gotoxy(6,2);
write(' ');
gotoxy(7,2);
write(' ');
gotoxy(8,2);
write(' ');
gotoxy(9,2);
write(' ');
gotoxy(20,2);
textbackground(5);
textcolor(0);
write(' ');
gotoxy(21,2);
write(' ');
gotoxy(22,2);
write(' ');
gotoxy(23,2);
write(' ');
gotoxy(24,2);
write(' ');
gotoxy(25,2);
write(' ');
gotoxy(26,2);
write(' ');
gotoxy(27,2);
write(' ');
gotoxy(38,2);
textbackground(6);
textcolor(0);
write(' ');
gotoxy(39,2);
write(' ');
gotoxy(52,2);
textbackground(1);
textcolor(0);
write(' ');
gotoxy(53,2);
write(' ');
textbackground(black);
textcolor(7);
gotoxy(71,2);
write('/');
gotoxy(73,2);
write('\');
gotoxy(1,3);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(2,3);
write(' ');
gotoxy(9,3);
textbackground(2);
write(' ');
gotoxy(10,3);
write(' ');
gotoxy(13,3);
textbackground(4);
write(' ');
gotoxy(14,3);
write(' ');
gotoxy(15,3);
write(' ');
gotoxy(16,3);
write(' ');
gotoxy(20,3);
textbackground(5);
write(' ');
gotoxy(22,3);
textbackground(5);
write(' ');
gotoxy(23,3);
write(' ');
gotoxy(24,3);
write(' ');
gotoxy(25,3);
write(' ');
gotoxy(27,3);
textbackground(5);
textcolor(0);
write(' ');
gotoxy(30,3);
textbackground(4);
write(' ');
gotoxy(31,3);
write(' ');
gotoxy(32,3);
write(' ');
gotoxy(33,3);
write(' ');
gotoxy(38,3);
textbackground(6);
textcolor(0);
write(' ');
gotoxy(39,3);
write(' ');
gotoxy(40,3);
write(' ');
gotoxy(41,3);
write(' ');
gotoxy(42,3);
write(' ');
gotoxy(45,3);
textbackground(4);
write(' ');
gotoxy(46,3);
write(' ');
gotoxy(47,3);
write(' ');
gotoxy(48,3);
write(' ');
gotoxy(52,3);
textbackground(1);
textcolor(0);
write(' ');
gotoxy(53,3);
write(' ');
textbackground(black);
textcolor(7);
gotoxy(70,3);
write('|');
gotoxy(72,3);
write('R');
gotoxy(74,3);
textcolor(7);
write('|');
gotoxy(1,4);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(2,4);
write(' ');
gotoxy(9,4);
textbackground(2);
write(' ');
gotoxy(10,4);
write(' ');
gotoxy(12,4);
textbackground(4);
write(' ');
gotoxy(17,4);
textbackground(4);
write(' ');
gotoxy(20,4);
textbackground(5);
textcolor(0);
write(' ');
gotoxy(26,4);
textbackground(5);
write(' ');
gotoxy(27,4);
write(' ');
gotoxy(29,4);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(34,4);
textbackground(4);
write(' ');
gotoxy(38,4);
textbackground(6);
textcolor(0);
write(' ');
gotoxy(39,4);
write(' ');
gotoxy(44,4);
textbackground(4);
write(' ');
gotoxy(49,4);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(52,4);
textbackground(1);
textcolor(0);
write(' ');
gotoxy(53,4);
write(' ');
gotoxy(55,4);
textbackground(1);
write(' ');
gotoxy(56,4);
write(' ');
gotoxy(57,4);
write(' ');
gotoxy(61,4);
textbackground(3);
textcolor(0);
write(' ');
gotoxy(62,4);
write(' ');
gotoxy(63,4);
write(' ');
gotoxy(64,4);
write(' ');
gotoxy(65,4);
write(' ');
gotoxy(66,4);
write(' ');
gotoxy(67,4);
write(' ');
gotoxy(71,4);
textbackground(black);
textcolor(7);
write('\');
gotoxy(72,4);
write('_');
gotoxy(73,4);
write('/');
gotoxy(1,5);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(2,5);
write(' ');
gotoxy(9,5);
textbackground(2);
write(' ');
gotoxy(10,5);
write(' ');
gotoxy(17,5);
textbackground(4);
write(' ');
gotoxy(20,5);
textbackground(5);
textcolor(0);
write(' ');
gotoxy(26,5);
textbackground(5);
write(' ');
gotoxy(27,5);
write(' ');
gotoxy(34,5);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(38,5);
textbackground(6);
textcolor(0);
write(' ');
gotoxy(39,5);
write(' ');
gotoxy(49,5);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(52,5);
textbackground(1);
textcolor(0);
write(' ');
gotoxy(53,5);
write(' ');
gotoxy(54,5);
write(' ');
gotoxy(55,5);
write(' ');
gotoxy(56,5);
write(' ');
gotoxy(57,5);
write(' ');
gotoxy(58,5);
write(' ');
gotoxy(61,5);
textbackground(3);
textcolor(0);
write(' ');
gotoxy(62,5);
write(' ');
gotoxy(63,5);
write(' ');
gotoxy(64,5);
write(' ');
gotoxy(65,5);
write(' ');
gotoxy(66,5);
write(' ');
gotoxy(67,5);
write(' ');
gotoxy(1,6);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(2,6);
write(' ');
gotoxy(9,6);
textbackground(2);
write(' ');
gotoxy(10,6);
write(' ');
gotoxy(17,6);
textbackground(4);
write(' ');
gotoxy(20,6);
textbackground(5);
textcolor(0);
write(' ');
gotoxy(21,6);
write(' ');
gotoxy(26,6);
textbackground(5);
write(' ');
gotoxy(27,6);
write(' ');
gotoxy(34,6);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(38,6);
textbackground(6);
textcolor(0);
write(' ');
gotoxy(39,6);
write(' ');
gotoxy(49,6);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(52,6);
textbackground(1);
textcolor(0);
write(' ');
gotoxy(53,6);
write(' ');
gotoxy(54,6);
write(' ');
gotoxy(57,6);
textbackground(1);
textcolor(0);
write(' ');
gotoxy(58,6);
write(' ');
gotoxy(59,6);
write(' ');
gotoxy(61,6);
textbackground(3);
textcolor(0);
write(' ');
gotoxy(62,6);
write(' ');
gotoxy(66,6);
textbackground(3);
textcolor(0);
write(' ');
gotoxy(67,6);
write(' ');
gotoxy(1,7);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(2,7);
write(' ');
gotoxy(9,7);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(10,7);
write(' ');
gotoxy(13,7);
textbackground(4);
write(' ');
gotoxy(14,7);
write(' ');
gotoxy(15,7);
write(' ');
gotoxy(16,7);
write(' ');
gotoxy(17,7);
write(' ');
gotoxy(20,7);
textbackground(5);
textcolor(0);
write(' ');
gotoxy(21,7);
write(' ');
gotoxy(22,7);
write(' ');
gotoxy(30,7);
textbackground(4);
write(' ');
gotoxy(31,7);
write(' ');
gotoxy(32,7);
write(' ');
gotoxy(33,7);
write(' ');
gotoxy(34,7);
write(' ');
gotoxy(38,7);
textbackground(6);
textcolor(0);
write(' ');
gotoxy(39,7);
write(' ');
gotoxy(45,7);
textbackground(4);
write(' ');
gotoxy(46,7);
write(' ');
gotoxy(47,7);
write(' ');
gotoxy(48,7);
write(' ');
gotoxy(49,7);
write(' ');
gotoxy(52,7);
textbackground(1);
textcolor(0);
write(' ');
gotoxy(53,7);
write(' ');
gotoxy(58,7);
textbackground(1);
textcolor(0);
write(' ');
gotoxy(59,7);
write(' ');
gotoxy(61,7);
textbackground(3);
textcolor(0);
write(' ');
gotoxy(62,7);
write(' ');
gotoxy(63,7);
write(' ');
gotoxy(64,7);
write(' ');
gotoxy(65,7);
write(' ');
gotoxy(66,7);
write(' ');
gotoxy(67,7);
write(' ');
gotoxy(1,8);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(2,8);
write(' ');
gotoxy(9,8);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(10,8);
write(' ');
gotoxy(12,8);
textbackground(4);
write(' ');
gotoxy(17,8);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(20,8);
textbackground(5);
textcolor(0);
write(' ');
gotoxy(21,8);
write(' ');
gotoxy(22,8);
write(' ');
gotoxy(23,8);
write(' ');
gotoxy(24,8);
write(' ');
gotoxy(25,8);
write(' ');
gotoxy(26,8);
write(' ');
gotoxy(27,8);
write(' ');
gotoxy(29,8);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(34,8);
textbackground(4);
write(' ');
gotoxy(38,8);
textbackground(6);
textcolor(0);
write(' ');
gotoxy(39,8);
write(' ');
gotoxy(42,8);
textbackground(6);
write(' ');
gotoxy(44,8);
textbackground(4);
write(' ');
gotoxy(49,8);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(52,8);
textbackground(1);
textcolor(0);
write(' ');
gotoxy(53,8);
write(' ');
gotoxy(54,8);
write(' ');
gotoxy(57,8);
textbackground(1);
textcolor(0);
write(' ');
gotoxy(58,8);
write(' ');
gotoxy(59,8);
write(' ');
gotoxy(61,8);
textbackground(3);
textcolor(0);
write(' ');
gotoxy(62,8);
write(' ');
gotoxy(1,9);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(2,9);
write(' ');
gotoxy(3,9);
write(' ');
gotoxy(4,9);
write(' ');
gotoxy(5,9);
write(' ');
gotoxy(6,9);
write(' ');
gotoxy(7,9);
write(' ');
gotoxy(8,9);
write(' ');
gotoxy(9,9);
write(' ');
gotoxy(12,9);
textbackground(4);
write(' ');
gotoxy(17,9);
textbackground(4);
write(' ');
gotoxy(25,9);
textbackground(5);
write(' ');
gotoxy(26,9);
write(' ');
gotoxy(27,9);
write(' ');
gotoxy(29,9);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(34,9);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(38,9);
textbackground(6);
textcolor(0);
write(' ');
gotoxy(39,9);
write(' ');
gotoxy(40,9);
write(' ');
gotoxy(41,9);
write(' ');
gotoxy(42,9);
write(' ');
gotoxy(44,9);
textbackground(4);
write(' ');
gotoxy(49,9);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(52,9);
textbackground(1);
textcolor(0);
write(' ');
gotoxy(53,9);
write(' ');
gotoxy(54,9);
write(' ');
gotoxy(55,9);
write(' ');
gotoxy(56,9);
write(' ');
gotoxy(57,9);
write(' ');
gotoxy(58,9);
write(' ');
gotoxy(61,9);
textbackground(3);
textcolor(0);
write(' ');
gotoxy(62,9);
write(' ');
gotoxy(66,9);
textbackground(3);
write(' ');
gotoxy(67,9);
write(' ');
gotoxy(1,10);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(2,10);
write(' ');
gotoxy(3,10);
write(' ');
gotoxy(4,10);
write(' ');
gotoxy(5,10);
write(' ');
gotoxy(6,10);
write(' ');
gotoxy(7,10);
write(' ');
gotoxy(8,10);
write(' ');
gotoxy(13,10);
textbackground(4);
write(' ');
gotoxy(14,10);
write(' ');
gotoxy(15,10);
write(' ');
gotoxy(16,10);
write(' ');
gotoxy(18,10);
textbackground(4);
write(' ');
gotoxy(20,10);
textbackground(5);
write(' ');
gotoxy(21,10);
write(' ');
gotoxy(26,10);
textbackground(5);
write(' ');
gotoxy(27,10);
write(' ');
gotoxy(30,10);
textbackground(4);
write(' ');
gotoxy(31,10);
write(' ');
gotoxy(32,10);
write(' ');
gotoxy(33,10);
write(' ');
gotoxy(35,10);
textbackground(4);
write(' ');
gotoxy(39,10);
textbackground(6);
write(' ');
gotoxy(40,10);
write(' ');
gotoxy(41,10);
write(' ');
gotoxy(45,10);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(46,10);
write(' ');
gotoxy(47,10);
write(' ');
gotoxy(48,10);
write(' ');
gotoxy(50,10);
textbackground(4);
write(' ');
gotoxy(52,10);
textbackground(1);
textcolor(0);
write(' ');
gotoxy(54,10);
textbackground(1);
write(' ');
gotoxy(55,10);
write(' ');
gotoxy(56,10);
write(' ');
gotoxy(57,10);
write(' ');
gotoxy(61,10);
textbackground(3);
textcolor(0);
write(' ');
gotoxy(62,10);
write(' ');
gotoxy(63,10);
write(' ');
gotoxy(64,10);
write(' ');
gotoxy(65,10);
write(' ');
gotoxy(66,10);
write(' ');
gotoxy(67,10);
write(' ');
gotoxy(20,11);
textbackground(5);
write(' ');
gotoxy(21,11);
write(' ');
gotoxy(27,11);
textbackground(5);
textcolor(0);
write(' ');
gotoxy(20,12);
textbackground(5);
textcolor(0);
write(' ');
gotoxy(21,12);
write(' ');
gotoxy(27,12);
textbackground(5);
textcolor(0);
write(' ');
gotoxy(20,13);
textbackground(5);
textcolor(0);
write(' ');
gotoxy(22,13);
textbackground(5);
write(' ');
gotoxy(23,13);
write(' ');
gotoxy(24,13);
write(' ');
gotoxy(25,13);
write(' ');
gotoxy(27,13);
textbackground(5);
textcolor(0);
write(' ');
gotoxy(20,14);
textbackground(5);
textcolor(0);
write(' ');
gotoxy(21,14);
write(' ');
gotoxy(22,14);
write(' ');
gotoxy(23,14);
write(' ');
gotoxy(24,14);
write(' ');
gotoxy(25,14);
write(' ');
gotoxy(26,14);
write(' ');
gotoxy(27,14);
write(' ');
end;

procedure newdasa;
begin
    textbackground(lightgray);
    textcolor(black);
    clrscr;
    for i:=1 to 50 do
        begin
             for k:=1 to 50 do att[i][k]:=0;
             name[i]:='';
             attname[i]:='';
        end;
    writeln('inserisci gli attributi che caratterizzeranno i records (massimo 3 attributi)');
    writeln;
    atts:=0;
    repeat
          atts:=atts+1;
          write('nome attributo? ');
          readln(attname[atts]);
          writeln;
          writeln('vuoi aggiungerne un altro? (s/n)');
          repeat
                c:=readkey;
          until (c='s')or(c='n')or(c='S')or(c='N');
    until (c='n')or(c='N')or(atts=50);
    writeln;
    writeln('inserisci i records');
    writeln;
    data:=0;
    repeat
          data:=data+1;
          writeln;
          writeln('inserisci il record nome del record (massimo 50) e caratterizzalo (s/n)');
          readln(name[data]);
          i:=0;
          repeat
             i:=i+1;
             write(attname[i],': ');
             repeat
                readln(c);
             until (c='s')or(c='n')or(c='S')or(c='N');
             if (c='n')or(c='N') then att[data][i]:=0
                                 else att[data][i]:=1;
          until i=atts;
          writeln('vuoi aggiungere un altro record? (s/n)');
          repeat
                c:=readkey;
          until (c='s')or(c='n')or(c='S')or(c='N');

    until (c='n')or(c='N')or(i=50);
    writeln('inserisci il percorso del database da creare');
    writeln('(l''estensione sara'' aggiunta automaticamente)');
    readln(percorso);
    assign(source,percorso+'.dst');
    rewrite(source);
    writeln(source,data);
    writeln(source,atts);
    for i:=1 to atts do writeln(source,attname[i]);
    for i:=1 to data do
        begin
             writeln(source,name[i]);
             for k:=1 to atts do writeln(source,att[i][k]);
        end;
    close(source);
    writeln;
    writeln('salvataggio completato con successo!');
    delay(1500);
end;

procedure openexisting;
begin
    textbackground(lightgray);
    textcolor(black);
    for i:=1 to 50 do
        begin
             for k:=1 to 50 do att[i][k]:=0;
             name[i]:='';
             attname[i]:='';
             for k:=1 to 50 do loc[k][i]:=0;
             if i<=50 then cursor[i]:=0;
        end;
    gotoxy(1,12);
    clrscr;
    writeln('inserisci il percorso del database .dst');
    writeln('(l''estensione e'' aggiunta automaticamente)');
    readln(percorso);
    assign(source,percorso+'.dst');
    reset(source);
    readln(source,data);
    readln(source,atts);
    for i:=1 to atts do readln(source,attname[i]);
    for i:=1 to data do
        begin
             readln(source,name[i]);
             for k:=1 to atts do readln(source,att[i][k]);
             for k:=1 to atts do
               if att[i][k]=1 then
                  begin
                     numrecs[k]:=numrecs[k]+1;
                     cursor[k]:=cursor[k]+1;loc[k][cursor[k]]:=i;
                  end;
        end;
    close(source);
    clrscr;
    writeln('apertura ',percorso);
    writeln;
    writeln(data,' elementi,',atts,' attributi');
    for k:=1 to atts do
         begin
              writeln;
              writeln(attname[k],': ',numrecs[k],' elementi');
              if cursor[k]>0 then for i:=1 to cursor[k] do write(name[loc[k][i]],' ');
              writeln;
         end;
    writeln;
    writeln;
    write('premere spazio per tornare al menu''');
    i:=0;
    repeat
          c:=readkey;
          writeln(i);
    until c=' ';
end;

procedure modexisting;
begin
end;

procedure info;
begin
    textbackground(green);
    clrscr;
    writeln;
    writeln;
    writeln;
    writeln;
    writeln;
    writeln;
    writeln;
    textcolor(lightgreen);
    writeln('                             DASATABE ULTIMATE');
    textcolor(white);
    writeln('                                         gestione databas... ehm, dasatabe');
    writeln;
    writeln('                       copyright Alessnadro Cacco 2012');
    writeln;
    writeln('                 grazie per aver utilizzato un mio programma :)');
    writeln;
    writeln;
    writeln;
    writeln;
    writeln('                     premi spazio per tornare al menu''...');
    repeat
          c:=readkey;
    until c=' ';
end;


begin
  repeat
    textcolor(lightgray);
    textbackground(black);
    clrscr;
    title;
    textcolor(lightgray);
    textbackground(black);
    gotoxy(55,11);writeln('gestionale database');
    gotoxy(25,23);writeln('copyright Alessandro Cacco 2012');
    i:=1;
    textcolor(black);
    repeat
          k:=749;
          textbackground(lightgray);
          gotoxy(32,13); write('-nuovo database-');
          gotoxy(32,15); write('--apri database-');
          gotoxy(32,17); write('--modifica dst--');
          gotoxy(32,19); write('-----about------');
          gotoxy(32,21); write('-----uscita-----');
          if i=1 then
                repeat
                      k:=k+1;
                      if k mod 1500=750 then  textbackground(yellow);
                      if k mod 1500=0 then  textbackground(lightgray);
                      gotoxy(32,13);
                      write('-nuovo database-');
                until keypressed;
          if i=2 then
                repeat
                      k:=k+1;
                      if k mod 1500=750 then  textbackground(yellow);
                      if k mod 1500=0 then  textbackground(lightgray);
                      gotoxy(32,15);
                      write('--apri database-');
                until keypressed;
          if i=3 then
                repeat
                      k:=k+1;
                      if k mod 1500=750 then  textbackground(yellow);
                      if k mod 1500=0 then  textbackground(lightgray);
                      gotoxy(32,17);
                      write('--modifica dst--');
                until keypressed;
          if i=4 then
                repeat
                      k:=k+1;
                      if k mod 1500=750 then  textbackground(lightgreen);
                      if k mod 1500=0 then  textbackground(lightgray);
                      gotoxy(32,19);
                      write('-----about------');
                until keypressed;
          if i=5 then
                repeat
                      k:=k+1;
                      if k mod 1500=750 then  textbackground(red);
                      if k mod 1500=0 then  textbackground(lightgray);
                      gotoxy(32,21);
                      write('-----uscita-----');
                until keypressed;
          c:=readkey;
          if c='w' then i:=i-1;
          if c='s' then i:=i+1;
          if i=0 then i:=5;
          if i=6 then i:=1;
    until c=' ';
    if i=1 then newdasa;
    if i=2 then openexisting;
    if i=3 then modexisting;
    if i=4 then info;
  until i=5;
end.

