program labirinth_auto_small;
uses crt;
var h,b,i,j,x,y,x0,y0,exx,exy,xf,yf:integer;
    area:array[1..100,1..100]of boolean;
    c:char;

procedure title;
begin
gotoxy(68,1);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(3,2);
textbackground(2);
write(' ');
gotoxy(4,2);
write(' ');
gotoxy(5,2);
write(' ');
gotoxy(6,2);
write(' ');
gotoxy(7,2);
write(' ');
gotoxy(12,2);
textbackground(2);
write(' ');
gotoxy(13,2);
write(' ');
gotoxy(14,2);
write(' ');
gotoxy(15,2);
write(' ');
gotoxy(16,2);
write(' ');
gotoxy(17,2);
write(' ');
gotoxy(18,2);
write(' ');
gotoxy(19,2);
write(' ');
gotoxy(20,2);
write(' ');
gotoxy(21,2);
write(' ');
gotoxy(23,2);
textbackground(2);
write(' ');
gotoxy(24,2);
write(' ');
gotoxy(25,2);
write(' ');
gotoxy(26,2);
write(' ');
gotoxy(27,2);
write(' ');
gotoxy(28,2);
write(' ');
gotoxy(29,2);
write(' ');
gotoxy(30,2);
write(' ');
gotoxy(31,2);
write(' ');
gotoxy(36,2);
textbackground(2);
write(' ');
gotoxy(37,2);
write(' ');
gotoxy(44,2);
textbackground(2);
write(' ');
gotoxy(45,2);
write(' ');
gotoxy(46,2);
write(' ');
gotoxy(47,2);
write(' ');
gotoxy(55,2);
textbackground(2);
write(' ');
gotoxy(56,2);
write(' ');
gotoxy(66,2);
textbackground(2);
write(' ');
gotoxy(67,2);
write(' ');
gotoxy(68,2);
write(' ');
gotoxy(69,2);
write(' ');
gotoxy(70,2);
write(' ');
gotoxy(3,3);
textbackground(2);
write(' ');
gotoxy(4,3);
write(' ');
gotoxy(5,3);
write(' ');
gotoxy(7,3);
textbackground(2);
write(' ');
gotoxy(12,3);
textbackground(2);
write(' ');
gotoxy(21,3);
textbackground(2);
write(' ');
gotoxy(23,3);
textbackground(2);
write(' ');
gotoxy(31,3);
textbackground(2);
write(' ');
gotoxy(34,3);
textbackground(2);
write(' ');
gotoxy(35,3);
write(' ');
gotoxy(36,3);
write(' ');
gotoxy(37,3);
write(' ');
gotoxy(43,3);
textbackground(2);
write(' ');
gotoxy(44,3);
write(' ');
gotoxy(45,3);
write(' ');
gotoxy(46,3);
write(' ');
gotoxy(47,3);
write(' ');
gotoxy(48,3);
write(' ');
gotoxy(55,3);
textbackground(2);
write(' ');
gotoxy(56,3);
write(' ');
gotoxy(68,3);
textbackground(2);
write(' ');
gotoxy(3,4);
textbackground(2);
write(' ');
gotoxy(4,4);
write(' ');
gotoxy(5,4);
write(' ');
gotoxy(7,4);
textbackground(2);
write(' ');
gotoxy(12,4);
textbackground(2);
write(' ');
gotoxy(15,4);
textbackground(2);
write(' ');
gotoxy(16,4);
write(' ');
gotoxy(17,4);
write(' ');
gotoxy(18,4);
write(' ');
gotoxy(21,4);
textbackground(2);
write(' ');
gotoxy(23,4);
textbackground(2);
write(' ');
gotoxy(26,4);
textbackground(2);
write(' ');
gotoxy(27,4);
write(' ');
gotoxy(28,4);
write(' ');
gotoxy(31,4);
textbackground(2);
write(' ');
gotoxy(34,4);
textbackground(2);
write(' ');
gotoxy(35,4);
write(' ');
gotoxy(37,4);
textbackground(2);
write(' ');
gotoxy(42,4);
textbackground(2);
write(' ');
gotoxy(43,4);
write(' ');
gotoxy(48,4);
textbackground(2);
write(' ');
gotoxy(53,4);
textbackground(2);
write(' ');
gotoxy(54,4);
write(' ');
gotoxy(55,4);
write(' ');
gotoxy(56,4);
write(' ');
gotoxy(57,4);
write(' ');
gotoxy(59,4);
textbackground(2);
write(' ');
gotoxy(60,4);
write(' ');
gotoxy(68,4);
textbackground(2);
write(' ');
gotoxy(71,4);
textbackground(2);
write(' ');
gotoxy(72,4);
write(' ');
gotoxy(73,4);
write(' ');
gotoxy(78,4);
textbackground(2);
write(' ');
gotoxy(79,4);
write(' ');
gotoxy(80,4);
write(' ');
gotoxy(3,5);
textbackground(2);
write(' ');
gotoxy(4,5);
write(' ');
gotoxy(5,5);
write(' ');
gotoxy(7,5);
textbackground(2);
write(' ');
gotoxy(12,5);
textbackground(2);
write(' ');
gotoxy(15,5);
textbackground(2);
write(' ');
gotoxy(18,5);
textbackground(2);
write(' ');
gotoxy(21,5);
textbackground(2);
write(' ');
gotoxy(23,5);
textbackground(2);
write(' ');
gotoxy(30,5);
textbackground(2);
write(' ');
gotoxy(31,5);
write(' ');
gotoxy(34,5);
textbackground(2);
write(' ');
gotoxy(36,5);
textbackground(2);
write(' ');
gotoxy(37,5);
write(' ');
gotoxy(42,5);
textbackground(2);
write(' ');
gotoxy(43,5);
write(' ');
gotoxy(45,5);
textbackground(2);
write(' ');
gotoxy(46,5);
write(' ');
gotoxy(48,5);
textbackground(2);
write(' ');
gotoxy(49,5);
write(' ');
gotoxy(53,5);
textbackground(2);
write(' ');
gotoxy(54,5);
write(' ');
gotoxy(55,5);
write(' ');
gotoxy(57,5);
textbackground(2);
write(' ');
gotoxy(59,5);
textbackground(2);
write(' ');
gotoxy(60,5);
write(' ');
gotoxy(61,5);
write(' ');
gotoxy(62,5);
write(' ');
gotoxy(63,5);
write(' ');
gotoxy(64,5);
write(' ');
gotoxy(68,5);
textbackground(2);
write(' ');
gotoxy(71,5);
textbackground(2);
write(' ');
gotoxy(72,5);
write(' ');
gotoxy(73,5);
write(' ');
gotoxy(78,5);
textbackground(2);
write(' ');
gotoxy(79,5);
write(' ');
gotoxy(80,5);
write(' ');
gotoxy(3,6);
textbackground(2);
write(' ');
gotoxy(4,6);
write(' ');
gotoxy(5,6);
write(' ');
gotoxy(7,6);
textbackground(2);
write(' ');
gotoxy(12,6);
textbackground(2);
write(' ');
gotoxy(15,6);
textbackground(2);
write(' ');
gotoxy(16,6);
write(' ');
gotoxy(17,6);
write(' ');
gotoxy(18,6);
write(' ');
gotoxy(21,6);
textbackground(2);
write(' ');
gotoxy(23,6);
textbackground(2);
write(' ');
gotoxy(25,6);
textbackground(2);
write(' ');
gotoxy(26,6);
write(' ');
gotoxy(27,6);
write(' ');
gotoxy(28,6);
write(' ');
gotoxy(31,6);
textbackground(2);
write(' ');
gotoxy(34,6);
textbackground(2);
write(' ');
gotoxy(35,6);
write(' ');
gotoxy(37,6);
textbackground(2);
write(' ');
gotoxy(42,6);
textbackground(2);
write(' ');
gotoxy(43,6);
write(' ');
gotoxy(48,6);
textbackground(2);
write(' ');
gotoxy(49,6);
write(' ');
gotoxy(53,6);
textbackground(2);
write(' ');
gotoxy(54,6);
write(' ');
gotoxy(55,6);
write(' ');
gotoxy(56,6);
write(' ');
gotoxy(57,6);
write(' ');
gotoxy(59,6);
textbackground(2);
write(' ');
gotoxy(60,6);
write(' ');
gotoxy(61,6);
write(' ');
gotoxy(62,6);
write(' ');
gotoxy(63,6);
write(' ');
gotoxy(64,6);
write(' ');
gotoxy(68,6);
textbackground(2);
write(' ');
gotoxy(71,6);
textbackground(2);
write(' ');
gotoxy(72,6);
write(' ');
gotoxy(73,6);
write(' ');
gotoxy(78,6);
textbackground(2);
write(' ');
gotoxy(79,6);
write(' ');
gotoxy(80,6);
write(' ');
gotoxy(3,7);
textbackground(2);
write(' ');
gotoxy(4,7);
write(' ');
gotoxy(5,7);
write(' ');
gotoxy(7,7);
textbackground(2);
write(' ');
gotoxy(8,7);
write(' ');
gotoxy(9,7);
write(' ');
gotoxy(12,7);
textbackground(2);
write(' ');
gotoxy(21,7);
textbackground(2);
write(' ');
gotoxy(23,7);
textbackground(2);
write(' ');
gotoxy(25,7);
textbackground(2);
write(' ');
gotoxy(26,7);
write(' ');
gotoxy(27,7);
write(' ');
gotoxy(28,7);
write(' ');
gotoxy(31,7);
textbackground(2);
write(' ');
gotoxy(34,7);
textbackground(2);
write(' ');
gotoxy(36,7);
textbackground(2);
write(' ');
gotoxy(37,7);
write(' ');
gotoxy(42,7);
textbackground(2);
write(' ');
gotoxy(43,7);
write(' ');
gotoxy(44,7);
write(' ');
gotoxy(45,7);
write(' ');
gotoxy(46,7);
write(' ');
gotoxy(47,7);
write(' ');
gotoxy(48,7);
write(' ');
gotoxy(49,7);
write(' ');
gotoxy(53,7);
textbackground(2);
write(' ');
gotoxy(54,7);
write(' ');
gotoxy(56,7);
textbackground(2);
write(' ');
gotoxy(57,7);
write(' ');
gotoxy(59,7);
textbackground(2);
write(' ');
gotoxy(60,7);
write(' ');
gotoxy(63,7);
textbackground(2);
write(' ');
gotoxy(64,7);
write(' ');
gotoxy(68,7);
textbackground(2);
write(' ');
gotoxy(71,7);
textbackground(2);
write(' ');
gotoxy(72,7);
write(' ');
gotoxy(73,7);
write(' ');
gotoxy(74,7);
write(' ');
gotoxy(75,7);
write(' ');
gotoxy(76,7);
write(' ');
gotoxy(77,7);
write(' ');
gotoxy(78,7);
write(' ');
gotoxy(79,7);
write(' ');
gotoxy(80,7);
write(' ');
gotoxy(3,8);
textbackground(2);
write(' ');
gotoxy(4,8);
write(' ');
gotoxy(5,8);
write(' ');
gotoxy(9,8);
textbackground(2);
write(' ');
gotoxy(12,8);
textbackground(2);
write(' ');
gotoxy(15,8);
textbackground(2);
write(' ');
gotoxy(16,8);
write(' ');
gotoxy(17,8);
write(' ');
gotoxy(18,8);
write(' ');
gotoxy(21,8);
textbackground(2);
write(' ');
gotoxy(23,8);
textbackground(2);
write(' ');
gotoxy(25,8);
textbackground(2);
write(' ');
gotoxy(26,8);
write(' ');
gotoxy(27,8);
write(' ');
gotoxy(30,8);
textbackground(2);
write(' ');
gotoxy(31,8);
write(' ');
gotoxy(34,8);
textbackground(2);
write(' ');
gotoxy(35,8);
write(' ');
gotoxy(37,8);
textbackground(2);
write(' ');
gotoxy(42,8);
textbackground(2);
write(' ');
gotoxy(43,8);
write(' ');
gotoxy(45,8);
textbackground(2);
write(' ');
gotoxy(46,8);
write(' ');
gotoxy(53,8);
textbackground(2);
write(' ');
gotoxy(54,8);
write(' ');
gotoxy(55,8);
write(' ');
gotoxy(56,8);
write(' ');
gotoxy(57,8);
write(' ');
gotoxy(59,8);
textbackground(2);
write(' ');
gotoxy(60,8);
write(' ');
gotoxy(63,8);
textbackground(2);
write(' ');
gotoxy(64,8);
write(' ');
gotoxy(68,8);
textbackground(2);
write(' ');
gotoxy(71,8);
textbackground(2);
write(' ');
gotoxy(72,8);
write(' ');
gotoxy(73,8);
write(' ');
gotoxy(74,8);
write(' ');
gotoxy(75,8);
write(' ');
gotoxy(76,8);
write(' ');
gotoxy(77,8);
write(' ');
gotoxy(78,8);
write(' ');
gotoxy(79,8);
write(' ');
gotoxy(80,8);
write(' ');
gotoxy(3,9);
textbackground(2);
write(' ');
gotoxy(4,9);
write(' ');
gotoxy(5,9);
write(' ');
gotoxy(6,9);
write(' ');
gotoxy(7,9);
write(' ');
gotoxy(8,9);
write(' ');
gotoxy(9,9);
write(' ');
gotoxy(12,9);
textbackground(2);
write(' ');
gotoxy(15,9);
textbackground(2);
write(' ');
gotoxy(18,9);
textbackground(2);
write(' ');
gotoxy(21,9);
textbackground(2);
write(' ');
gotoxy(23,9);
textbackground(2);
write(' ');
gotoxy(26,9);
textbackground(2);
write(' ');
gotoxy(29,9);
textbackground(2);
write(' ');
gotoxy(30,9);
write(' ');
gotoxy(33,9);
textbackground(2);
write(' ');
gotoxy(34,9);
write(' ');
gotoxy(36,9);
textbackground(2);
write(' ');
gotoxy(37,9);
write(' ');
gotoxy(38,9);
write(' ');
gotoxy(42,9);
textbackground(2);
write(' ');
gotoxy(43,9);
write(' ');
gotoxy(45,9);
textbackground(2);
write(' ');
gotoxy(46,9);
write(' ');
gotoxy(47,9);
write(' ');
gotoxy(53,9);
textbackground(2);
write(' ');
gotoxy(55,9);
textbackground(2);
write(' ');
gotoxy(56,9);
write(' ');
gotoxy(57,9);
write(' ');
gotoxy(68,9);
textbackground(2);
write(' ');
gotoxy(71,9);
textbackground(2);
write(' ');
gotoxy(72,9);
write(' ');
gotoxy(73,9);
write(' ');
gotoxy(74,9);
write(' ');
gotoxy(75,9);
write(' ');
gotoxy(76,9);
write(' ');
gotoxy(77,9);
write(' ');
gotoxy(78,9);
write(' ');
gotoxy(79,9);
write(' ');
gotoxy(80,9);
write(' ');
gotoxy(3,10);
textbackground(2);
write(' ');
gotoxy(4,10);
write(' ');
gotoxy(5,10);
write(' ');
gotoxy(6,10);
write(' ');
gotoxy(7,10);
write(' ');
gotoxy(8,10);
write(' ');
gotoxy(9,10);
write(' ');
gotoxy(12,10);
textbackground(2);
write(' ');
gotoxy(13,10);
write(' ');
gotoxy(14,10);
write(' ');
gotoxy(15,10);
write(' ');
gotoxy(18,10);
textbackground(2);
write(' ');
gotoxy(21,10);
textbackground(2);
write(' ');
gotoxy(23,10);
textbackground(2);
write(' ');
gotoxy(28,10);
textbackground(2);
write(' ');
gotoxy(29,10);
write(' ');
gotoxy(32,10);
textbackground(2);
write(' ');
gotoxy(33,10);
write(' ');
gotoxy(35,10);
textbackground(2);
write(' ');
gotoxy(37,10);
textbackground(2);
write(' ');
gotoxy(38,10);
write(' ');
gotoxy(39,10);
write(' ');
gotoxy(42,10);
textbackground(2);
write(' ');
gotoxy(43,10);
write(' ');
gotoxy(46,10);
textbackground(2);
write(' ');
gotoxy(47,10);
write(' ');
gotoxy(48,10);
write(' ');
gotoxy(49,10);
write(' ');
gotoxy(53,10);
textbackground(2);
write(' ');
gotoxy(54,10);
write(' ');
gotoxy(55,10);
write(' ');
gotoxy(57,10);
textbackground(2);
write(' ');
gotoxy(68,10);
textbackground(2);
write(' ');
gotoxy(71,10);
textbackground(2);
write(' ');
gotoxy(72,10);
write(' ');
gotoxy(73,10);
write(' ');
gotoxy(78,10);
textbackground(2);
write(' ');
gotoxy(79,10);
write(' ');
gotoxy(80,10);
write(' ');
gotoxy(3,11);
textbackground(2);
write(' ');
gotoxy(4,11);
write(' ');
gotoxy(5,11);
write(' ');
gotoxy(6,11);
write(' ');
gotoxy(7,11);
write(' ');
gotoxy(8,11);
write(' ');
gotoxy(9,11);
write(' ');
gotoxy(18,11);
textbackground(2);
write(' ');
gotoxy(19,11);
write(' ');
gotoxy(20,11);
write(' ');
gotoxy(21,11);
write(' ');
gotoxy(23,11);
textbackground(2);
write(' ');
gotoxy(24,11);
write(' ');
gotoxy(25,11);
write(' ');
gotoxy(26,11);
write(' ');
gotoxy(27,11);
write(' ');
gotoxy(28,11);
write(' ');
gotoxy(31,11);
textbackground(2);
write(' ');
gotoxy(32,11);
write(' ');
gotoxy(33,11);
write(' ');
gotoxy(34,11);
write(' ');
gotoxy(35,11);
write(' ');
gotoxy(36,11);
write(' ');
gotoxy(37,11);
write(' ');
gotoxy(38,11);
write(' ');
gotoxy(39,11);
write(' ');
gotoxy(42,11);
textbackground(2);
write(' ');
gotoxy(43,11);
write(' ');
gotoxy(46,11);
textbackground(2);
write(' ');
gotoxy(47,11);
write(' ');
gotoxy(48,11);
write(' ');
gotoxy(49,11);
write(' ');
gotoxy(53,11);
textbackground(2);
write(' ');
gotoxy(54,11);
write(' ');
gotoxy(55,11);
write(' ');
gotoxy(56,11);
write(' ');
gotoxy(57,11);
write(' ');
gotoxy(68,11);
textbackground(2);
write(' ');
gotoxy(71,11);
textbackground(2);
write(' ');
gotoxy(72,11);
write(' ');
gotoxy(73,11);
write(' ');
gotoxy(78,11);
textbackground(2);
write(' ');
gotoxy(79,11);
write(' ');
gotoxy(80,11);
write(' ');
end;

procedure difficulty;
var lev:integer;
begin
     clrscr;
     textbackground(7);
     for j:=1 to 11 do
         for i:=1 to 80 do
             begin
                  gotoxy(i,j);
                  write(' ');
             end;     title;

     textbackground(black);
     textcolor(7);
     gotoxy(3,17);
     write('EASY');
     gotoxy(38,17);
     write('MEDIUM');
     gotoxy(75,17);
     write('HARD');
     gotoxy(1,12);
     writeln(chr(201));
     writeln(chr(186));
     writeln(chr(186));
     writeln(chr(186));
     writeln(chr(200));
     gotoxy(80,12);
     write(chr(187));
     gotoxy(80,13);
     write(chr(186));
     gotoxy(80,14);
     write(chr(186));
     gotoxy(80,15);
     write(chr(186));
     gotoxy(80,16);
     write(chr(188));
     for i:=2 to 79 do
         begin
              gotoxy(i,12);
              write(chr(205));
              gotoxy(i,16);
              write(chr(205));
         end;
     gotoxy(1,1);
     lev:=30;
     textbackground(red);
     for j:=2 to lev do
       for i:=13 to 15 do
         begin
              gotoxy(j,i);
              write(' ');
         end;
     repeat
           c:=readkey;
           if c=#0 then
                  begin
                       c:=readkey;
                       case c of
                            #75:if lev-1>1 then
                                   begin
                                        textbackground(black);
                                        for i:=13 to 15 do
                                            begin
                                                 gotoxy(lev,i);
                                                 write(' ');
                                            end;
                                        lev:=lev-1;
                                        textbackground(red);
                                        for i:=13 to 15 do
                                            begin
                                                 gotoxy(lev,i);
                                                 write(' ');
                                            end;
                                   end;
                            #77:if lev+1<80 then
                                   begin
                                        lev:=lev+1;
                                        textbackground(red);
                                        for i:=13 to 15 do
                                            begin
                                                 gotoxy(lev,i);
                                                 write(' ');
                                            end;
                                   end;
                       end;
                  end;
           if c=#13 then c:=' ';
     until c=' ';
     lev:=lev+21;
     h:=lev;
     b:=lev;
end;

procedure generate;
var
   dir,ten,xx,yy:integer;
begin
   repeat
     for i:=1 to b do
         for j:=1 to h do
             area[i,j]:=true;
     x:=random(b)+1;
     y:=random(h)+1;
     area[x,y]:=false;
     x0:=x;
     y0:=y;
     xx:=x;
     yy:=y;
     j:=0;
     for i:=1 to (b*h)div 30 do
          begin
              ten:=0;
              repeat
                    ten:=ten+1;
                    dir:=random(4);                                                                            //                                                                                            //                                                                                            //
              until ((dir=0)and(yy>0)and(area[xx,yy-2]=true)and(area[xx-1,yy-1]=true)and(area[xx+1,yy-1]=true))or((dir=1)and(xx<=b)and(area[xx+2,yy]=true)and(area[xx+1,yy-1]=true)and(area[xx+1,yy+1]=true))or((dir=2)and(yy<=h)and(area[xx,yy+2]=true)and(area[xx-1,yy+1]=true)and(area[xx+1,yy+1]=true))or((dir=3)and(xx>0)and(area[xx-2,yy]=true)and(area[xx-1,yy-1]=true)and(area[xx-1,yy+1]=true))or(ten>=10);
              if ten<10 then
                case dir of                                                                                      //                                                                                            //                                                                                            //
                   0:yy:=yy-1;
                   1:xx:=xx+1;
                   2:yy:=yy+1;
                   3:xx:=xx-1;
                end;
              if ten>=10 then j:=1;
              area[xx,yy]:=false;
          end;
     xf:=xx;
     yf:=yy;
   until j=0;
     for j:=1 to (b*h)div 20 do
       begin
            repeat
                xx:=random(b)+1;
                yy:=random(h)+1;
            until area[xx,yy]=false;
          for i:=1 to (b*h)div 30 do
            begin
              ten:=0;
              repeat
                    ten:=ten+1;
                    dir:=random(4);                                                                            //                                                                                            //                                                                                            //
              until ((dir=0)and(yy>0)and(area[xx,yy-2]=true)and(area[xx-1,yy-1]=true)and(area[xx+1,yy-1]=true))or((dir=1)and(xx<=b)and(area[xx+2,yy]=true)and(area[xx+1,yy-1]=true)and(area[xx+1,yy+1]=true))or((dir=2)and(yy<=h)and(area[xx,yy+2]=true)and(area[xx-1,yy+1]=true)and(area[xx+1,yy+1]=true))or((dir=3)and(xx>0)and(area[xx-2,yy]=true)and(area[xx-1,yy-1]=true)and(area[xx-1,yy+1]=true))or(ten>=10);
              if ten<10 then
                case dir of                                                                                      //                                                                                            //                                                                                            //
                   0:yy:=yy-1;
                   1:xx:=xx+1;
                   2:yy:=yy+1;
                   3:xx:=xx-1;
                end;
              area[xx,yy]:=false;
            end;
       end;
end;

procedure show;
begin
     if xf+39<b then gotoxy(xf+39,yf)
                 else gotoxy(b,yf);
     if yf-12>0 then gotoxy(xf,yf-12)
                 else gotoxy(xf,1);
     if yf+12<h then gotoxy(xf,yf+12)
                 else gotoxy(xf,h);
     if xf-39>0 then gotoxy(xf-39,yf)
                 else gotoxy(1,yf);
     i:=xf;
     j:=yf;
     gotoxy(i,j);
     delay(1000);
     repeat
           if x<i then i:=i-1;
           if x>i then i:=i+1;
           if y<j then j:=j-1;
           if y>j then j:=j+1;
           if i+39<b then gotoxy(i+39,j)
                          else gotoxy(b,j);
           if j-12>0 then gotoxy(i,j-12)
                        else gotoxy(i,1);
           if j+12<h then gotoxy(i,j+12)
                          else gotoxy(i,h);
           if i-39>0 then gotoxy(i-39,j)
                        else gotoxy(1,j);
           gotoxy(i,j);
           delay(100);
     until ((i=x)and(j=y))or keypressed;
     i:=x;
     j:=y;
     if i+39<b then gotoxy(i+39,j)
               else gotoxy(b,j);
     if j-12>0 then gotoxy(i,j-12)
               else gotoxy(i,1);
     if j+12<h then gotoxy(i,j+12)
               else gotoxy(i,h);
     if i-39>0 then gotoxy(i-39,j)
               else gotoxy(1,j);
end;

procedure writescreen;
begin
     textbackground(0);
     clrscr;
     for i:=1 to h do
         for j:=1 to b do
             begin
                  gotoxy(j,i);
                  if area[j,i] then
                               begin
                                    textbackground(green);
                                    write('°');
                               end
                               else
                               begin
                                    textbackground(7);
                                    write(' ');
                               end;
             end;
     gotoxy(xf,yf);
     textbackground(red);
     write(' ');
     gotoxy(x,y);
     textbackground(blue);
     write(chr(1));
end;

procedure remember;
begin
     exx:=x;
     exy:=y;
end;

procedure move;
begin
     if x+39<b then gotoxy(x+39,y)
               else gotoxy(b,y);
     if y-12>0 then gotoxy(x,y-12)
               else gotoxy(x,1);
     if y+12<h then gotoxy(x,y+12)
               else gotoxy(x,h);
     if x-39>0 then gotoxy(x-39,y)
               else gotoxy(1,y);
     gotoxy(x,y);
     c:=readkey;
     case c of
          'a':x:=x-1;
          'd':x:=x+1;
          'w':y:=y-1;
          's':y:=y+1;
          'r':
              begin
                   x:=x0;
                   y:=y0;
              end;
          'g':show;
          #0:
             begin
               c:=readkey;
               case c of
                  #75:x:=x-1;
                  #77:x:=x+1;                           //FRECCE!!!!!!!!!!! :D:D:D
                  #80:y:=y+1;
                  #72:y:=y-1;
               end;
             end;
     end;
     if (area[x,y])or(x<=0)or(x>b)or(y<=0)or(y>h) then
        begin
             x:=exx;
             y:=exy;
        end;
     gotoxy(exx,exy);
     textbackground(7);
     write(' ');
     gotoxy(x,y);
     textbackground(blue);
     write(' ');
end;

function arrive:boolean;
begin
     arrive:=false;
     if (x=xf)and (y=yf) then arrive:=true;
end;

procedure whattodo;
begin
     textbackground(0);
     clrscr;
     if (x=xf)and(y=yf) then writeln('HAI VINTO!')
                        else writeln('HAI PERSO');
     writeln;
     writeln('press ''q'' key to quit, any other key to repeat game');
     c:=readkey;
end;

begin
   repeat
     difficulty;
     randomize;
     generate;
     writescreen;
     show;
     repeat
           remember;
           move;
     until (arrive)or(c='q');
     whattodo;
   until (c='q');
end.
