program letteresurichiesta;
uses crt;
var c:char;
    locx,locy,i:integer;
procedure let_A (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(2+x,5+y);
write(' ');
gotoxy(3+x,0+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,5+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,3+y);
write(' ');
gotoxy(5+x,4+y);
write(' ');
gotoxy(5+x,5+y);
write(' ');
gotoxy(5+x,6+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');
gotoxy(5+x,8+y);
write(' ');

end;
procedure let_B (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,3+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(2+x,7+y);
write(' ');
gotoxy(2+x,8+y);
write(' ');
gotoxy(3+x,0+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,2+y);
write(' ');
gotoxy(3+x,3+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,5+y);
write(' ');
gotoxy(3+x,6+y);
write(' ');
gotoxy(3+x,7+y);
write(' ');
gotoxy(3+x,8+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,5+y);
write(' ');
gotoxy(5+x,6+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');

end;
procedure let_C (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,2+y);
write(' ');
gotoxy(2+x,6+y);
write(' ');
gotoxy(2+x,7+y);
write(' ');
gotoxy(2+x,8+y);
write(' ');
gotoxy(3+x,0+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,2+y);
write(' ');
gotoxy(3+x,6+y);
write(' ');
gotoxy(3+x,7+y);
write(' ');
gotoxy(3+x,8+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,3+y);
write(' ');
gotoxy(5+x,5+y);
write(' ');
gotoxy(5+x,6+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');
gotoxy(5+x,8+y);
write(' ');

end;
procedure let_D (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,7+y);
write(' ');
gotoxy(2+x,8+y);
write(' ');
gotoxy(3+x,0+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,2+y);
write(' ');
gotoxy(3+x,6+y);
write(' ');
gotoxy(3+x,7+y);
write(' ');
gotoxy(3+x,8+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,3+y);
write(' ');
gotoxy(5+x,4+y);
write(' ');
gotoxy(5+x,5+y);
write(' ');
gotoxy(5+x,6+y);
write(' ');

end;
procedure let_E (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,2+y);
write(' ');
gotoxy(2+x,3+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(2+x,5+y);
write(' ');
gotoxy(2+x,6+y);
write(' ');
gotoxy(2+x,7+y);
write(' ');
gotoxy(2+x,8+y);
write(' ');
gotoxy(3+x,0+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,7+y);
write(' ');
gotoxy(3+x,8+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');
gotoxy(5+x,8+y);
write(' ');

end;
procedure let_F (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(2+x,5+y);
write(' ');
gotoxy(3+x,0+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,5+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');

end;
procedure let_G (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,7+y);
write(' ');
gotoxy(2+x,8+y);
write(' ');
gotoxy(3+x,0+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,5+y);
write(' ');
gotoxy(3+x,7+y);
write(' ');
gotoxy(3+x,8+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,4+y);
write(' ');
gotoxy(5+x,5+y);
write(' ');
gotoxy(5+x,6+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');
gotoxy(5+x,8+y);
write(' ');

end;
procedure let_H (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(2+x,5+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,5+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,3+y);
write(' ');
gotoxy(5+x,4+y);
write(' ');
gotoxy(5+x,5+y);
write(' ');
gotoxy(5+x,6+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');
gotoxy(5+x,8+y);
write(' ');

end;
procedure let_I (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,2+y);
write(' ');
gotoxy(2+x,3+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(2+x,5+y);
write(' ');
gotoxy(2+x,6+y);
write(' ');
gotoxy(2+x,7+y);
write(' ');
gotoxy(2+x,8+y);
write(' ');
gotoxy(3+x,0+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,2+y);
write(' ');
gotoxy(3+x,3+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,5+y);
write(' ');
gotoxy(3+x,6+y);
write(' ');
gotoxy(3+x,7+y);
write(' ');
gotoxy(3+x,8+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');
gotoxy(5+x,8+y);
write(' ');

end;
procedure let_J (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,2+y);
write(' ');
gotoxy(2+x,7+y);
write(' ');
gotoxy(2+x,8+y);
write(' ');
gotoxy(3+x,0+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,2+y);
write(' ');
gotoxy(3+x,3+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,5+y);
write(' ');
gotoxy(3+x,6+y);
write(' ');
gotoxy(3+x,7+y);
write(' ');
gotoxy(3+x,8+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');

end;
procedure let_K (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,3+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(2+x,5+y);
write(' ');
gotoxy(3+x,2+y);
write(' ');
gotoxy(3+x,3+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,5+y);
write(' ');
gotoxy(3+x,6+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,6+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');
gotoxy(5+x,8+y);
write(' ');

end;
procedure let_L (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,2+y);
write(' ');
gotoxy(2+x,3+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(2+x,5+y);
write(' ');
gotoxy(2+x,6+y);
write(' ');
gotoxy(2+x,7+y);
write(' ');
gotoxy(2+x,8+y);
write(' ');
gotoxy(3+x,7+y);
write(' ');
gotoxy(3+x,8+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');
gotoxy(5+x,8+y);
write(' ');

end;
procedure let_M (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,2+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,2+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,3+y);
write(' ');
gotoxy(5+x,4+y);
write(' ');
gotoxy(5+x,5+y);
write(' ');
gotoxy(5+x,6+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');

end;
procedure let_N (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,2+y);
write(' ');
gotoxy(2+x,3+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(3+x,3+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,5+y);
write(' ');
gotoxy(3+x,6+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,3+y);
write(' ');
gotoxy(5+x,4+y);
write(' ');
gotoxy(5+x,5+y);
write(' ');
gotoxy(5+x,6+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');
gotoxy(5+x,8+y);
write(' ');
gotoxy(79+x,3+y);
write(' ');

end;
procedure let_O (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,7+y);
write(' ');
gotoxy(2+x,8+y);
write(' ');
gotoxy(3+x,0+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,7+y);
write(' ');
gotoxy(3+x,8+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,3+y);
write(' ');
gotoxy(5+x,4+y);
write(' ');
gotoxy(5+x,5+y);
write(' ');
gotoxy(5+x,6+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');

end;
procedure let_P (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,3+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(3+x,0+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,3+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,3+y);
write(' ');

end;
procedure let_Q (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,7+y);
write(' ');
gotoxy(2+x,8+y);
write(' ');
gotoxy(3+x,0+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,6+y);
write(' ');
gotoxy(3+x,7+y);
write(' ');
gotoxy(3+x,8+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,3+y);
write(' ');
gotoxy(5+x,4+y);
write(' ');
gotoxy(5+x,5+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');
gotoxy(5+x,8+y);
write(' ');

end;
procedure let_R (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,3+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(2+x,5+y);
write(' ');
gotoxy(3+x,0+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,3+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,5+y);
write(' ');
gotoxy(3+x,6+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,3+y);
write(' ');
gotoxy(5+x,4+y);
write(' ');
gotoxy(5+x,6+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');
gotoxy(5+x,8+y);
write(' ');

end;
procedure let_S (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,3+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(2+x,7+y);
write(' ');
gotoxy(2+x,8+y);
write(' ');
gotoxy(3+x,0+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,5+y);
write(' ');
gotoxy(3+x,7+y);
write(' ');
gotoxy(3+x,8+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,5+y);
write(' ');
gotoxy(5+x,6+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');

end;
procedure let_T (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,2+y);
write(' ');
gotoxy(2+x,3+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(2+x,5+y);
write(' ');
gotoxy(2+x,6+y);
write(' ');
gotoxy(2+x,7+y);
write(' ');
gotoxy(2+x,8+y);
write(' ');
gotoxy(3+x,0+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,2+y);
write(' ');
gotoxy(3+x,3+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,5+y);
write(' ');
gotoxy(3+x,6+y);
write(' ');
gotoxy(3+x,7+y);
write(' ');
gotoxy(3+x,8+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');

end;
procedure let_U (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,6+y);
write(' ');
gotoxy(2+x,7+y);
write(' ');
gotoxy(2+x,8+y);
write(' ');
gotoxy(3+x,6+y);
write(' ');
gotoxy(3+x,7+y);
write(' ');
gotoxy(3+x,8+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,3+y);
write(' ');
gotoxy(5+x,4+y);
write(' ');
gotoxy(5+x,5+y);
write(' ');
gotoxy(5+x,6+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');

end;
procedure let_V (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(2+x,6+y);
write(' ');
gotoxy(2+x,7+y);
write(' ');
gotoxy(2+x,8+y);
write(' ');
gotoxy(3+x,6+y);
write(' ');
gotoxy(3+x,7+y);
write(' ');
gotoxy(3+x,8+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,3+y);
write(' ');
gotoxy(5+x,4+y);
write(' ');
gotoxy(5+x,5+y);
write(' ');

end;
procedure let_W (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,3+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(2+x,5+y);
write(' ');
gotoxy(2+x,6+y);
write(' ');
gotoxy(2+x,7+y);
write(' ');
gotoxy(3+x,3+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,5+y);
write(' ');
gotoxy(3+x,6+y);
write(' ');
gotoxy(3+x,7+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,3+y);
write(' ');
gotoxy(5+x,4+y);
write(' ');
gotoxy(5+x,5+y);
write(' ');
gotoxy(5+x,6+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');
gotoxy(5+x,8+y);
write(' ');

end;
procedure let_X (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,2+y);
write(' ');
gotoxy(2+x,3+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(2+x,5+y);
write(' ');
gotoxy(2+x,6+y);
write(' ');
gotoxy(3+x,2+y);
write(' ');
gotoxy(3+x,3+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,5+y);
write(' ');
gotoxy(3+x,6+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,6+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');
gotoxy(5+x,8+y);
write(' ');

end;
procedure let_Y (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(2+x,3+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(2+x,5+y);
write(' ');
gotoxy(2+x,6+y);
write(' ');
gotoxy(2+x,7+y);
write(' ');
gotoxy(2+x,8+y);
write(' ');
gotoxy(3+x,3+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,5+y);
write(' ');
gotoxy(3+x,6+y);
write(' ');
gotoxy(3+x,7+y);
write(' ');
gotoxy(3+x,8+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,3+y);
write(' ');
gotoxy(5+x,4+y);
write(' ');

end;
procedure let_Z (x,y:integer);
begin
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(2+x,5+y);
write(' ');
gotoxy(2+x,7+y);
write(' ');
gotoxy(2+x,8+y);
write(' ');
gotoxy(3+x,0+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,3+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,7+y);
write(' ');
gotoxy(3+x,8+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');
gotoxy(5+x,8+y);
write(' ');
end;




begin
textbackground(white);
textcolor(black);
c:='1';
repeat
repeat
      if c='1' then clrscr;
      textbackground(white);
      gotoxy(1,1);
      gotoxy(1,25);
      write('lettera:'' ''');
      gotoxy(10,25);
      read(c);
      gotoxy(1,1);
      if (c<>'0')and(c<>'1') then
      begin
      gotoxy(20,25);
      write('coordinate:(  .  )');
      gotoxy(32,25);
      readln(locx);
      gotoxy(1,1);
      gotoxy(35,25);
      readln(locy);
      end;
until (locx<75)and(locy<16);
if c='q' then let_q(locx,locy);
if c='w' then let_w(locx,locy);
if c='e' then let_e(locx,locy);
if c='r' then let_r(locx,locy);
if c='t' then let_t(locx,locy);
if c='y' then let_y(locx,locy);
if c='u' then let_u(locx,locy);
if c='i' then let_i(locx,locy);
if c='o' then let_o(locx,locy);
if c='p' then let_p(locx,locy);
if c='a' then let_a(locx,locy);
if c='s' then let_s(locx,locy);
if c='d' then let_d(locx,locy);
if c='f' then let_f(locx,locy);
if c='g' then let_g(locx,locy);
if c='h' then let_h(locx,locy);
if c='j' then let_j(locx,locy);
if c='k' then let_k(locx,locy);
if c='l' then let_l(locx,locy);
if c='z' then let_z(locx,locy);
if c='x' then let_x(locx,locy);
if c='c' then let_c(locx,locy);
if c='v' then let_v(locx,locy);
if c='b' then let_b(locx,locy);
if c='n' then let_n(locx,locy);
if c='m' then let_m(locx,locy);
until c='0';
end.

