(*programma per la gestione di  una biblioteca, ideato e creato per
Livieri Tommaso,  giugno 2013, sviluppato nell'estate seguente con una lentezza
fuori da ogni grazia di Dio, sostanzialmente inutile visti programmi con questo
scopo con archivi di codici a barre sulle spalle e una grafica molto più sviluppata.
credo che andrò ben poco avanti con questo lavoro, mi dispiace che non renda affatto
la fatica che ho speso per scriverlo, non è affatto semplice ed intuitivo il
codice, tuttavia mi asterrò volontariamente e incontrovertibilissimamente dal
commentarlo. merita di essere finito, ma ne riconosco la sua grande inutilità, ad oggi 14/9/2013*)
program orglib;
uses crt;
type
    data=record
         d,m,y:string[2];
    end;
    book=record
         shelf:integer;
         outby,name,author,editor,prize,pages,year:string;
         outt,red,reading:boolean;
         datains:data;
    end;

var
    sc,k,i,j,part:integer;
    c:char;
    commands:array[1..5] of string;
    quitpar:boolean;
    books:array[1..10000]of book;
    list:array[1..10000] of integer;
    request:string;
    code:word;
    numreq,selbook:integer;

procedure title;
begin
textbackground(3);
clrscr;
gotoxy(2,1);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(3,1);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(4,1);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(5,1);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(6,1);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(7,1);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(8,1);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(11,1);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(12,1);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,1);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(31,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(32,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(33,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(34,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(35,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(36,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(37,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(38,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(39,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(40,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(41,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(42,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(43,1);
textbackground(4);
textcolor(6);
write(' ');
gotoxy(44,1);
textbackground(4);
textcolor(6);
write(' ');
gotoxy(45,1);
textbackground(4);
textcolor(6);
write(' ');
gotoxy(46,1);
textbackground(4);
textcolor(6);
write(' ');
gotoxy(47,1);
textbackground(4);
textcolor(6);
write(' ');
gotoxy(48,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(49,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(50,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(51,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(52,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(53,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(54,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(55,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(56,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(57,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(58,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(59,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(60,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(61,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(62,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(63,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(64,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(65,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(66,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(67,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(68,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(69,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(70,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(71,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(72,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(73,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(74,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(75,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(76,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(77,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(78,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(79,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(80,1);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(2,2);
textbackground(0);
write(' ');
gotoxy(3,2);
write(' ');
gotoxy(4,2);
write(' ');
gotoxy(5,2);
write(' ');
gotoxy(6,2);
write(' ');
gotoxy(7,2);
write(' ');
gotoxy(8,2);
write(' ');
gotoxy(10,2);
textbackground(0);
write(' ');
gotoxy(11,2);
write(' ');
gotoxy(12,2);
write(' ');
gotoxy(13,2);
write(' ');
gotoxy(14,2);
write(' ');
gotoxy(24,2);
textbackground(1);
write(' ');
gotoxy(25,2);
write(' ');
gotoxy(26,2);
write(' ');
gotoxy(27,2);
write(' ');
gotoxy(28,2);
write(' ');
gotoxy(29,2);
write(' ');
gotoxy(30,2);
write(' ');
gotoxy(31,2);
write(' ');
gotoxy(32,2);
write(' ');
gotoxy(33,2);
write(' ');
gotoxy(34,2);
write(' ');
gotoxy(35,2);
write(' ');
gotoxy(36,2);
write(' ');
gotoxy(37,2);
write(' ');
gotoxy(38,2);
write(' ');
gotoxy(39,2);
write(' ');
gotoxy(40,2);
write(' ');
gotoxy(41,2);
write(' ');
gotoxy(42,2);
write(' ');
gotoxy(43,2);
textbackground(4);
textcolor(6);
write(' ');
gotoxy(44,2);
textbackground(0);
write(' ');
gotoxy(45,2);
write(' ');
gotoxy(46,2);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(47,2);
textcolor(6);
write(' ');
gotoxy(48,2);
textcolor(0);
write(' ');
gotoxy(54,2);
textbackground(5);
textcolor(6);
write(' ');
gotoxy(55,2);
write(' ');
gotoxy(56,2);
write(' ');
gotoxy(65,2);
textbackground(4);
write(' ');
gotoxy(66,2);
write(' ');
gotoxy(67,2);
write(' ');
gotoxy(79,2);
textbackground(4);
write(' ');
gotoxy(80,2);
write(' ');
gotoxy(2,3);
textbackground(0);
write(' ');
gotoxy(3,3);
write(' ');
gotoxy(7,3);
textbackground(0);
write(' ');
gotoxy(8,3);
write(' ');
gotoxy(10,3);
textbackground(0);
write(' ');
gotoxy(11,3);
write(' ');
gotoxy(13,3);
textbackground(0);
write(' ');
gotoxy(14,3);
write(' ');
gotoxy(17,3);
textbackground(0);
write(' ');
gotoxy(18,3);
write(' ');
gotoxy(19,3);
write(' ');
gotoxy(20,3);
write(' ');
gotoxy(21,3);
write(' ');
gotoxy(24,3);
textbackground(1);
write(' ');
gotoxy(42,3);
textbackground(1);
write(' ');
gotoxy(44,3);
textbackground(0);
textcolor(6);
write(' ');
gotoxy(45,3);
write(' ');
gotoxy(47,3);
textbackground(4);
write(' ');
gotoxy(51,3);
textbackground(1);
textcolor(6);
write(' ');
gotoxy(52,3);
write(' ');
gotoxy(54,3);
textbackground(5);
textcolor(6);
write(' ');
gotoxy(55,3);
write(' ');
gotoxy(56,3);
write(' ');
gotoxy(57,3);
textbackground(7);
write(' ');
gotoxy(66,3);
textbackground(4);
write(' ');
gotoxy(80,3);
textbackground(4);
write(' ');
gotoxy(2,4);
textbackground(0);
write(' ');
gotoxy(3,4);
write(' ');
gotoxy(7,4);
textbackground(0);
write(' ');
gotoxy(8,4);
write(' ');
gotoxy(10,4);
textbackground(0);
write(' ');
gotoxy(11,4);
write(' ');
gotoxy(16,4);
textbackground(0);
write(' ');
gotoxy(17,4);
write(' ');
gotoxy(18,4);
write(' ');
gotoxy(19,4);
write(' ');
gotoxy(20,4);
write(' ');
gotoxy(21,4);
write(' ');
gotoxy(22,4);
write(' ');
gotoxy(24,4);
textbackground(1);
write(' ');
gotoxy(42,4);
textbackground(1);
write(' ');
gotoxy(44,4);
textbackground(0);
textcolor(6);
write(' ');
gotoxy(45,4);
write(' ');
gotoxy(47,4);
textbackground(4);
write(' ');
gotoxy(51,4);
textbackground(1);
textcolor(6);
write(' ');
gotoxy(52,4);
write(' ');
gotoxy(53,4);
textbackground(6);
write(' ');
gotoxy(54,4);
textbackground(5);
write(' ');
gotoxy(55,4);
write(' ');
gotoxy(56,4);
write(' ');
gotoxy(57,4);
textbackground(7);
write(' ');
gotoxy(58,4);
textbackground(6);
textcolor(0);
write(' ');
gotoxy(59,4);
write(' ');
gotoxy(60,4);
write(' ');
gotoxy(61,4);
write(' ');
gotoxy(62,4);
write(' ');
gotoxy(63,4);
write(' ');
gotoxy(64,4);
write(' ');
gotoxy(66,4);
textbackground(4);
write(' ');
gotoxy(80,4);
textbackground(4);
write(' ');
gotoxy(2,5);
textbackground(0);
write(' ');
gotoxy(3,5);
write(' ');
gotoxy(7,5);
textbackground(0);
write(' ');
gotoxy(8,5);
write(' ');
gotoxy(10,5);
textbackground(0);
write(' ');
gotoxy(11,5);
write(' ');
gotoxy(16,5);
textbackground(0);
write(' ');
gotoxy(17,5);
write(' ');
gotoxy(21,5);
textbackground(0);
write(' ');
gotoxy(22,5);
write(' ');
gotoxy(24,5);
textbackground(1);
write(' ');
gotoxy(42,5);
textbackground(1);
write(' ');
gotoxy(44,5);
textbackground(0);
textcolor(6);
write(' ');
gotoxy(45,5);
write(' ');
gotoxy(47,5);
textbackground(4);
write(' ');
gotoxy(49,5);
textbackground(2);
textcolor(6);
write(' ');
gotoxy(50,5);
write(' ');
gotoxy(51,5);
textbackground(1);
write(' ');
gotoxy(52,5);
write(' ');
gotoxy(53,5);
textbackground(6);
write(' ');
gotoxy(54,5);
textbackground(5);
write(' ');
gotoxy(55,5);
write(' ');
gotoxy(56,5);
write(' ');
gotoxy(57,5);
textbackground(7);
write(' ');
gotoxy(58,5);
textbackground(5);
textcolor(0);
write(' ');
gotoxy(59,5);
write(' ');
gotoxy(60,5);
write(' ');
gotoxy(61,5);
write(' ');
gotoxy(62,5);
write(' ');
gotoxy(63,5);
write(' ');
gotoxy(64,5);
write(' ');
gotoxy(65,5);
write(' ');
gotoxy(66,5);
textbackground(4);
write(' ');
gotoxy(80,5);
textbackground(4);
write(' ');
gotoxy(2,6);
textbackground(0);
write(' ');
gotoxy(3,6);
write(' ');
gotoxy(7,6);
textbackground(0);
write(' ');
gotoxy(8,6);
write(' ');
gotoxy(10,6);
textbackground(0);
write(' ');
gotoxy(11,6);
write(' ');
gotoxy(16,6);
textbackground(0);
write(' ');
gotoxy(17,6);
write(' ');
gotoxy(21,6);
textbackground(0);
write(' ');
gotoxy(22,6);
write(' ');
gotoxy(24,6);
textbackground(1);
write(' ');
gotoxy(42,6);
textbackground(1);
write(' ');
gotoxy(44,6);
textbackground(0);
textcolor(6);
write(' ');
gotoxy(45,6);
write(' ');
gotoxy(47,6);
textbackground(4);
write(' ');
gotoxy(49,6);
textbackground(2);
textcolor(6);
write(' ');
gotoxy(50,6);
write(' ');
gotoxy(51,6);
textbackground(1);
write(' ');
gotoxy(52,6);
write(' ');
gotoxy(53,6);
textbackground(6);
write(' ');
gotoxy(54,6);
textbackground(5);
write(' ');
gotoxy(55,6);
write(' ');
gotoxy(56,6);
write(' ');
gotoxy(57,6);
textbackground(7);
write(' ');
gotoxy(58,6);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(59,6);
write(' ');
gotoxy(60,6);
write(' ');
gotoxy(61,6);
write(' ');
gotoxy(62,6);
write(' ');
gotoxy(66,6);
textbackground(4);
write(' ');
gotoxy(80,6);
textbackground(4);
write(' ');
gotoxy(2,7);
textbackground(0);
write(' ');
gotoxy(3,7);
write(' ');
gotoxy(4,7);
write(' ');
gotoxy(5,7);
write(' ');
gotoxy(6,7);
write(' ');
gotoxy(7,7);
write(' ');
gotoxy(8,7);
write(' ');
gotoxy(10,7);
textbackground(0);
write(' ');
gotoxy(11,7);
write(' ');
gotoxy(16,7);
textbackground(0);
write(' ');
gotoxy(17,7);
write(' ');
gotoxy(18,7);
write(' ');
gotoxy(19,7);
write(' ');
gotoxy(20,7);
write(' ');
gotoxy(21,7);
write(' ');
gotoxy(22,7);
write(' ');
gotoxy(24,7);
textbackground(1);
write(' ');
gotoxy(42,7);
textbackground(1);
write(' ');
gotoxy(44,7);
textbackground(0);
textcolor(6);
write(' ');
gotoxy(45,7);
write(' ');
gotoxy(47,7);
textbackground(4);
write(' ');
gotoxy(49,7);
textbackground(2);
textcolor(6);
write(' ');
gotoxy(50,7);
write(' ');
gotoxy(51,7);
textbackground(1);
write(' ');
gotoxy(52,7);
write(' ');
gotoxy(53,7);
textbackground(6);
write(' ');
gotoxy(54,7);
textbackground(5);
write(' ');
gotoxy(55,7);
write(' ');
gotoxy(56,7);
write(' ');
gotoxy(57,7);
textbackground(7);
write(' ');
gotoxy(59,7);
textbackground(0);
write(' ');
gotoxy(60,7);
write(' ');
gotoxy(61,7);
write(' ');
gotoxy(62,7);
write(' ');
gotoxy(63,7);
write(' ');
gotoxy(64,7);
write(' ');
gotoxy(66,7);
textbackground(4);
write(' ');
gotoxy(80,7);
textbackground(4);
write(' ');
gotoxy(2,8);
textbackground(0);
write(' ');
gotoxy(3,8);
write(' ');
gotoxy(4,8);
write(' ');
gotoxy(5,8);
write(' ');
gotoxy(6,8);
write(' ');
gotoxy(7,8);
write(' ');
gotoxy(8,8);
write(' ');
gotoxy(10,8);
textbackground(0);
write(' ');
gotoxy(11,8);
write(' ');
gotoxy(17,8);
textbackground(0);
write(' ');
gotoxy(18,8);
write(' ');
gotoxy(19,8);
write(' ');
gotoxy(20,8);
write(' ');
gotoxy(21,8);
write(' ');
gotoxy(22,8);
write(' ');
gotoxy(24,8);
textbackground(1);
write(' ');
gotoxy(25,8);
write(' ');
gotoxy(26,8);
write(' ');
gotoxy(27,8);
write(' ');
gotoxy(28,8);
write(' ');
gotoxy(29,8);
write(' ');
gotoxy(30,8);
write(' ');
gotoxy(31,8);
write(' ');
gotoxy(32,8);
write(' ');
gotoxy(33,8);
write(' ');
gotoxy(34,8);
write(' ');
gotoxy(35,8);
write(' ');
gotoxy(36,8);
write(' ');
gotoxy(37,8);
write(' ');
gotoxy(38,8);
write(' ');
gotoxy(39,8);
write(' ');
gotoxy(40,8);
write(' ');
gotoxy(41,8);
write(' ');
gotoxy(42,8);
write(' ');
gotoxy(43,8);
textbackground(4);
textcolor(6);
write(' ');
gotoxy(44,8);
textbackground(0);
write(' ');
gotoxy(45,8);
write(' ');
gotoxy(46,8);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(47,8);
textcolor(6);
write(' ');
gotoxy(48,8);
textcolor(0);
write(' ');
gotoxy(49,8);
textbackground(2);
textcolor(6);
write(' ');
gotoxy(50,8);
write(' ');
gotoxy(51,8);
textbackground(1);
write(' ');
gotoxy(52,8);
write(' ');
gotoxy(53,8);
textbackground(6);
write(' ');
gotoxy(54,8);
textbackground(5);
write(' ');
gotoxy(55,8);
write(' ');
gotoxy(56,8);
write(' ');
gotoxy(57,8);
textbackground(7);
write(' ');
gotoxy(58,8);
textbackground(2);
write(' ');
gotoxy(59,8);
write(' ');
gotoxy(60,8);
write(' ');
gotoxy(61,8);
write(' ');
gotoxy(62,8);
write(' ');
gotoxy(63,8);
write(' ');
gotoxy(64,8);
write(' ');
gotoxy(65,8);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(66,8);
write(' ');
gotoxy(80,8);
textbackground(4);
write(' ');
gotoxy(1,9);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(2,9);
write(' ');
gotoxy(3,9);
write(' ');
gotoxy(4,9);
write(' ');
gotoxy(5,9);
write(' ');
gotoxy(6,9);
write(' ');
gotoxy(7,9);
write(' ');
gotoxy(8,9);
write(' ');
gotoxy(9,9);
write(' ');
gotoxy(10,9);
write(' ');
gotoxy(11,9);
write(' ');
gotoxy(12,9);
write(' ');
gotoxy(13,9);
write(' ');
gotoxy(14,9);
write(' ');
gotoxy(15,9);
write(' ');
gotoxy(16,9);
write(' ');
gotoxy(17,9);
write(' ');
gotoxy(18,9);
write(' ');
gotoxy(19,9);
write(' ');
gotoxy(20,9);
write(' ');
gotoxy(21,9);
textbackground(0);
write(' ');
gotoxy(22,9);
write(' ');
gotoxy(23,9);
textbackground(4);
write(' ');
gotoxy(24,9);
write(' ');
gotoxy(25,9);
write(' ');
gotoxy(26,9);
write(' ');
gotoxy(27,9);
write(' ');
gotoxy(28,9);
write(' ');
gotoxy(29,9);
write(' ');
gotoxy(30,9);
write(' ');
gotoxy(31,9);
write(' ');
gotoxy(32,9);
write(' ');
gotoxy(33,9);
write(' ');
gotoxy(34,9);
write(' ');
gotoxy(35,9);
write(' ');
gotoxy(36,9);
write(' ');
gotoxy(37,9);
write(' ');
gotoxy(38,9);
write(' ');
gotoxy(39,9);
write(' ');
gotoxy(40,9);
write(' ');
gotoxy(41,9);
write(' ');
gotoxy(42,9);
write(' ');
gotoxy(43,9);
textcolor(6);
write(' ');
gotoxy(44,9);
write(' ');
gotoxy(45,9);
write(' ');
gotoxy(46,9);
write(' ');
gotoxy(47,9);
write(' ');
gotoxy(48,9);
textcolor(0);
write(' ');
gotoxy(49,9);
textcolor(6);
write(' ');
gotoxy(50,9);
write(' ');
gotoxy(51,9);
textcolor(0);
write(' ');
gotoxy(52,9);
write(' ');
gotoxy(53,9);
write(' ');
gotoxy(54,9);
write(' ');
gotoxy(55,9);
write(' ');
gotoxy(56,9);
write(' ');
gotoxy(57,9);
write(' ');
gotoxy(58,9);
write(' ');
gotoxy(59,9);
write(' ');
gotoxy(60,9);
write(' ');
gotoxy(61,9);
write(' ');
gotoxy(62,9);
write(' ');
gotoxy(63,9);
write(' ');
gotoxy(64,9);
write(' ');
gotoxy(65,9);
write(' ');
gotoxy(66,9);
write(' ');
gotoxy(80,9);
textbackground(4);
write(' ');
gotoxy(10,10);
textbackground(1);
write(' ');
gotoxy(11,10);
write(' ');
gotoxy(12,10);
write(' ');
gotoxy(16,10);
textbackground(0);
write(' ');
gotoxy(17,10);
write(' ');
gotoxy(21,10);
textbackground(0);
write(' ');
gotoxy(22,10);
write(' ');
gotoxy(23,10);
textbackground(4);
write(' ');
gotoxy(24,10);
write(' ');
gotoxy(25,10);
write(' ');
gotoxy(26,10);
write(' ');
gotoxy(27,10);
write(' ');
gotoxy(28,10);
write(' ');
gotoxy(29,10);
write(' ');
gotoxy(30,10);
write(' ');
gotoxy(31,10);
write(' ');
gotoxy(32,10);
write(' ');
gotoxy(33,10);
textcolor(6);
write(' ');
gotoxy(34,10);
write(' ');
gotoxy(35,10);
textcolor(0);
write(' ');
gotoxy(36,10);
write(' ');
gotoxy(37,10);
write(' ');
gotoxy(38,10);
write(' ');
gotoxy(39,10);
write(' ');
gotoxy(40,10);
write(' ');
gotoxy(41,10);
write(' ');
gotoxy(42,10);
write(' ');
gotoxy(66,10);
textbackground(4);
write(' ');
gotoxy(80,10);
textbackground(4);
write(' ');
gotoxy(10,11);
textbackground(1);
write(' ');
gotoxy(11,11);
write(' ');
gotoxy(12,11);
write(' ');
gotoxy(16,11);
textbackground(0);
write(' ');
gotoxy(17,11);
write(' ');
gotoxy(18,11);
write(' ');
gotoxy(19,11);
write(' ');
gotoxy(20,11);
write(' ');
gotoxy(21,11);
write(' ');
gotoxy(22,11);
write(' ');
gotoxy(23,11);
textbackground(5);
write(' ');
gotoxy(24,11);
write(' ');
gotoxy(25,11);
write(' ');
gotoxy(31,11);
textbackground(4);
write(' ');
gotoxy(66,11);
textbackground(4);
write(' ');
gotoxy(80,11);
textbackground(4);
write(' ');
gotoxy(10,12);
textbackground(1);
write(' ');
gotoxy(11,12);
write(' ');
gotoxy(12,12);
write(' ');
gotoxy(17,12);
textbackground(0);
write(' ');
gotoxy(18,12);
write(' ');
gotoxy(19,12);
write(' ');
gotoxy(20,12);
write(' ');
gotoxy(21,12);
write(' ');
gotoxy(23,12);
textbackground(5);
write(' ');
gotoxy(24,12);
write(' ');
gotoxy(25,12);
write(' ');
gotoxy(31,12);
textbackground(4);
write(' ');
gotoxy(66,12);
textbackground(4);
write(' ');
gotoxy(67,12);
write(' ');
gotoxy(79,12);
textbackground(4);
write(' ');
gotoxy(80,12);
write(' ');
gotoxy(10,13);
textbackground(1);
write(' ');
gotoxy(11,13);
write(' ');
gotoxy(12,13);
write(' ');
gotoxy(17,13);
textbackground(6);
write(' ');
gotoxy(18,13);
write(' ');
gotoxy(19,13);
write(' ');
gotoxy(23,13);
textbackground(5);
write(' ');
gotoxy(24,13);
write(' ');
gotoxy(25,13);
write(' ');
gotoxy(31,13);
textbackground(4);
write(' ');
gotoxy(66,13);
textbackground(4);
write(' ');
gotoxy(67,13);
write(' ');
gotoxy(68,13);
write(' ');
gotoxy(69,13);
write(' ');
gotoxy(70,13);
write(' ');
gotoxy(71,13);
write(' ');
gotoxy(72,13);
write(' ');
gotoxy(73,13);
write(' ');
gotoxy(74,13);
write(' ');
gotoxy(75,13);
write(' ');
gotoxy(76,13);
write(' ');
gotoxy(77,13);
write(' ');
gotoxy(78,13);
write(' ');
gotoxy(79,13);
write(' ');
gotoxy(80,13);
write(' ');
gotoxy(10,14);
textbackground(1);
write(' ');
gotoxy(11,14);
write(' ');
gotoxy(12,14);
write(' ');
gotoxy(17,14);
textbackground(6);
write(' ');
gotoxy(18,14);
write(' ');
gotoxy(19,14);
write(' ');
gotoxy(21,14);
textbackground(7);
write(' ');
gotoxy(22,14);
write(' ');
gotoxy(23,14);
write(' ');
gotoxy(24,14);
write(' ');
gotoxy(25,14);
write(' ');
gotoxy(26,14);
write(' ');
gotoxy(27,14);
write(' ');
gotoxy(31,14);
textbackground(4);
write(' ');
gotoxy(80,14);
textbackground(4);
write(' ');
gotoxy(10,15);
textbackground(1);
write(' ');
gotoxy(11,15);
write(' ');
gotoxy(12,15);
write(' ');
gotoxy(17,15);
textbackground(6);
write(' ');
gotoxy(18,15);
write(' ');
gotoxy(19,15);
write(' ');
gotoxy(21,15);
textbackground(7);
write(' ');
gotoxy(22,15);
write(' ');
gotoxy(23,15);
write(' ');
gotoxy(24,15);
write(' ');
gotoxy(25,15);
write(' ');
gotoxy(26,15);
write(' ');
gotoxy(27,15);
write(' ');
gotoxy(28,15);
write(' ');
gotoxy(31,15);
textbackground(4);
write(' ');
gotoxy(80,15);
textbackground(4);
write(' ');
gotoxy(10,16);
textbackground(1);
write(' ');
gotoxy(11,16);
write(' ');
gotoxy(12,16);
write(' ');
gotoxy(17,16);
textbackground(6);
write(' ');
gotoxy(18,16);
write(' ');
gotoxy(19,16);
write(' ');
gotoxy(21,16);
textbackground(7);
write(' ');
gotoxy(22,16);
write(' ');
gotoxy(23,16);
textbackground(5);
write(' ');
gotoxy(24,16);
write(' ');
gotoxy(25,16);
write(' ');
gotoxy(26,16);
textbackground(7);
write(' ');
gotoxy(27,16);
write(' ');
gotoxy(28,16);
write(' ');
gotoxy(31,16);
textbackground(4);
write(' ');
gotoxy(80,16);
textbackground(4);
write(' ');
gotoxy(10,17);
textbackground(1);
write(' ');
gotoxy(11,17);
write(' ');
gotoxy(12,17);
write(' ');
gotoxy(17,17);
textbackground(6);
write(' ');
gotoxy(18,17);
write(' ');
gotoxy(19,17);
write(' ');
gotoxy(21,17);
textbackground(7);
write(' ');
gotoxy(22,17);
write(' ');
gotoxy(23,17);
textbackground(5);
write(' ');
gotoxy(24,17);
write(' ');
gotoxy(25,17);
write(' ');
gotoxy(26,17);
write(' ');
gotoxy(27,17);
textbackground(7);
write(' ');
gotoxy(28,17);
write(' ');
gotoxy(31,17);
textbackground(4);
write(' ');
gotoxy(80,17);
textbackground(4);
write(' ');
gotoxy(10,18);
textbackground(1);
write(' ');
gotoxy(11,18);
write(' ');
gotoxy(12,18);
write(' ');
gotoxy(13,18);
write(' ');
gotoxy(14,18);
write(' ');
gotoxy(15,18);
write(' ');
gotoxy(17,18);
textbackground(6);
write(' ');
gotoxy(18,18);
write(' ');
gotoxy(19,18);
write(' ');
gotoxy(21,18);
textbackground(7);
write(' ');
gotoxy(22,18);
write(' ');
gotoxy(23,18);
textbackground(5);
write(' ');
gotoxy(24,18);
write(' ');
gotoxy(25,18);
write(' ');
gotoxy(26,18);
textbackground(7);
write(' ');
gotoxy(27,18);
write(' ');
gotoxy(28,18);
write(' ');
gotoxy(31,18);
textbackground(4);
write(' ');
gotoxy(80,18);
textbackground(4);
write(' ');
gotoxy(10,19);
textbackground(1);
write(' ');
gotoxy(11,19);
write(' ');
gotoxy(12,19);
write(' ');
gotoxy(13,19);
write(' ');
gotoxy(14,19);
write(' ');
gotoxy(15,19);
write(' ');
gotoxy(17,19);
textbackground(6);
write(' ');
gotoxy(18,19);
write(' ');
gotoxy(19,19);
write(' ');
gotoxy(21,19);
textbackground(7);
write(' ');
gotoxy(22,19);
write(' ');
gotoxy(23,19);
write(' ');
gotoxy(24,19);
write(' ');
gotoxy(25,19);
write(' ');
gotoxy(26,19);
write(' ');
gotoxy(27,19);
write(' ');
gotoxy(31,19);
textbackground(4);
write(' ');
gotoxy(80,19);
textbackground(4);
write(' ');
gotoxy(10,20);
textbackground(1);
write(' ');
gotoxy(11,20);
write(' ');
gotoxy(12,20);
write(' ');
gotoxy(13,20);
write(' ');
gotoxy(14,20);
write(' ');
gotoxy(15,20);
write(' ');
gotoxy(17,20);
textbackground(6);
write(' ');
gotoxy(18,20);
write(' ');
gotoxy(19,20);
write(' ');
gotoxy(21,20);
textbackground(7);
write(' ');
gotoxy(22,20);
write(' ');
gotoxy(23,20);
textbackground(5);
write(' ');
gotoxy(24,20);
write(' ');
gotoxy(25,20);
write(' ');
gotoxy(26,20);
textbackground(7);
write(' ');
gotoxy(27,20);
write(' ');
gotoxy(28,20);
write(' ');
gotoxy(31,20);
textbackground(4);
write(' ');
gotoxy(80,20);
textbackground(4);
write(' ');
gotoxy(2,21);
textbackground(6);
textcolor(6);
write(' ');
gotoxy(3,21);
write(' ');
gotoxy(4,21);
write(' ');
gotoxy(17,21);
textbackground(6);
write(' ');
gotoxy(18,21);
write(' ');
gotoxy(19,21);
write(' ');
gotoxy(21,21);
textbackground(7);
write(' ');
gotoxy(22,21);
write(' ');
gotoxy(23,21);
textbackground(5);
write(' ');
gotoxy(24,21);
write(' ');
gotoxy(25,21);
write(' ');
gotoxy(26,21);
write(' ');
gotoxy(27,21);
textbackground(7);
write(' ');
gotoxy(28,21);
write(' ');
gotoxy(31,21);
textbackground(4);
write(' ');
gotoxy(80,21);
textbackground(4);
write(' ');
gotoxy(2,22);
textbackground(6);
textcolor(6);
write(' ');
gotoxy(4,22);
textbackground(6);
textcolor(6);
write(' ');
gotoxy(6,22);
textbackground(6);
textcolor(0);
write(' ');
gotoxy(7,22);
write(' ');
gotoxy(8,22);
write(' ');
gotoxy(17,22);
textbackground(6);
write(' ');
gotoxy(18,22);
write(' ');
gotoxy(19,22);
write(' ');
gotoxy(21,22);
textbackground(7);
write(' ');
gotoxy(22,22);
write(' ');
gotoxy(23,22);
textbackground(5);
write(' ');
gotoxy(24,22);
write(' ');
gotoxy(25,22);
write(' ');
gotoxy(26,22);
textbackground(7);
write(' ');
gotoxy(27,22);
write(' ');
gotoxy(28,22);
write(' ');
gotoxy(31,22);
textbackground(4);
write(' ');
gotoxy(80,22);
textbackground(4);
write(' ');
gotoxy(2,23);
textbackground(6);
textcolor(6);
write(' ');
gotoxy(3,23);
write(' ');
gotoxy(4,23);
write(' ');
gotoxy(6,23);
textbackground(6);
textcolor(0);
write(' ');
gotoxy(21,23);
textbackground(7);
write(' ');
gotoxy(22,23);
write(' ');
gotoxy(23,23);
write(' ');
gotoxy(24,23);
write(' ');
gotoxy(25,23);
write(' ');
gotoxy(26,23);
write(' ');
gotoxy(27,23);
write(' ');
gotoxy(28,23);
write(' ');
gotoxy(31,23);
textbackground(4);
write(' ');
gotoxy(32,23);
write(' ');
gotoxy(79,23);
textbackground(4);
write(' ');
gotoxy(80,23);
write(' ');
gotoxy(2,24);
textbackground(6);
textcolor(6);
write(' ');
gotoxy(4,24);
textbackground(6);
textcolor(6);
write(' ');
gotoxy(5,24);
textbackground(3);
write('.');
gotoxy(6,24);
textbackground(6);
textcolor(0);
write(' ');
gotoxy(7,24);
write(' ');
gotoxy(8,24);
write(' ');
gotoxy(9,24);
textbackground(3);
textcolor(6);
write('.');
gotoxy(21,24);
textbackground(7);
write(' ');
gotoxy(22,24);
write(' ');
gotoxy(23,24);
write(' ');
gotoxy(24,24);
write(' ');
gotoxy(25,24);
write(' ');
gotoxy(26,24);
write(' ');
gotoxy(27,24);
write(' ');
gotoxy(31,24);
textbackground(4);
write(' ');
gotoxy(32,24);
write(' ');
gotoxy(33,24);
write(' ');
gotoxy(34,24);
write(' ');
gotoxy(35,24);
write(' ');
gotoxy(36,24);
write(' ');
gotoxy(37,24);
write(' ');
gotoxy(38,24);
write(' ');
gotoxy(39,24);
write(' ');
gotoxy(40,24);
write(' ');
gotoxy(41,24);
write(' ');
gotoxy(42,24);
write(' ');
gotoxy(43,24);
write(' ');
gotoxy(44,24);
write(' ');
gotoxy(45,24);
write(' ');
gotoxy(46,24);
write(' ');
gotoxy(47,24);
write(' ');
gotoxy(48,24);
write(' ');
gotoxy(49,24);
write(' ');
gotoxy(50,24);
write(' ');
gotoxy(51,24);
write(' ');
gotoxy(52,24);
write(' ');
gotoxy(53,24);
write(' ');
gotoxy(54,24);
write(' ');
gotoxy(55,24);
write(' ');
gotoxy(56,24);
write(' ');
gotoxy(57,24);
write(' ');
gotoxy(58,24);
write(' ');
gotoxy(59,24);
write(' ');
gotoxy(60,24);
write(' ');
gotoxy(61,24);
write(' ');
gotoxy(62,24);
write(' ');
gotoxy(63,24);
write(' ');
gotoxy(64,24);
write(' ');
gotoxy(65,24);
write(' ');
gotoxy(66,24);
write(' ');
gotoxy(67,24);
write(' ');
gotoxy(68,24);
write(' ');
gotoxy(69,24);
write(' ');
gotoxy(70,24);
write(' ');
gotoxy(71,24);
write(' ');
gotoxy(72,24);
write(' ');
gotoxy(73,24);
write(' ');
gotoxy(74,24);
write(' ');
gotoxy(75,24);
write(' ');
gotoxy(76,24);
write(' ');
gotoxy(77,24);
write(' ');
gotoxy(78,24);
write(' ');
gotoxy(79,24);
write(' ');
gotoxy(80,24);
write(' ');
gotoxy(29,4);
textbackground(3);
textcolor(0);
write('copyright');
gotoxy(26,5);
write('Cacco Alessandro');
gotoxy(31,6);
write('2013');
end;

function compare(term1,term2:string; long:integer):boolean;
var p:integer;
begin
     compare:=true;
     for p:=1 to long do
         if term1[p]<>term2[p] then compare:=false;
end;

function isnum(req:string):boolean;
begin
     isnum:=true;
     for i:=1 to length(req)do
         if (req[i]<>'0')
            and(req[i]<>'1')
            and(req[i]<>'2')
            and(req[i]<>'3')
            and(req[i]<>'4')
            and(req[i]<>'5')
            and(req[i]<>'6')
            and(req[i]<>'7')
            and(req[i]<>'8')
            and(req[i]<>'9')
            then isnum:=false;
     if length(req)=0 then isnum:=false;
end;

procedure loadlib(where:string);
var lib:text;
    line:string;
    s,b:integer;
begin
     for i:=1 to 10000 do
         with books[i] do
              begin
                   author:='-no author-';
                   name:='-no name-';
                   editor:='------------';
                   outby:='--';
                   year:='----';
                   prize:='-----';
                   pages:='-----';
                   outt:=false;
                   red:=false;
                   reading:=false;
                   datains.y:='--';
                   datains.m:='--';
                   datains.d:='--';
              end;
     s:=0;
     b:=0;
     assign(lib,where);
     reset(lib);
     repeat
           readln(lib,line);
           if compare('shelf',line,5) then s:=s+1;
           if compare('book',line,4)then
              begin
                   b:=b+1;
                   books[b].shelf:=s;
              end;
           if compare('author',line,6)then
              begin
                   readln(lib,line);
                   books[b].author:=line;
              end;
           if compare('editor',line,6)then
              begin
                   readln(lib,line);
                   books[b].editor:=line;
              end;
           if compare('name',line,4)then
              begin
                   readln(lib,line);
                   books[b].name:=line;
              end;
           if compare('outby',line,5)then
              begin
                   readln(lib,line);
                   books[b].outby:=line;
              end;
           if compare('prize',line,5)then
              begin
                   readln(lib,line);
                   books[b].prize:=line;
              end;
           if compare('pages',line,5)then
              begin
                   readln(lib,line);
                   books[b].pages:=line;
              end;
           if compare('out',line,3)then
              begin
                   books[b].outt:=true;
              end;
           if compare('red',line,3)then
              begin
                   books[b].red:=true;
              end;
           if compare('reading',line,7)then
              begin
                   books[b].reading:=true;
              end;
           if compare('datains',line,7)then
              begin
                   readln(lib,line);
                   books[b].datains.d:=line;
                   readln(lib,line);
                   books[b].datains.m:=line;
                   readln(lib,line);
                   books[b].datains.y:=line;
              end;
           if compare('year',line,4)then
              begin
                   readln(lib,line);
                   books[b].year:=line;
              end;
     until eof(lib);
     close(lib);
end;

function anybookthere(s:integer):boolean;
begin
     anybookthere:=false;
     for j:=1 to 10000 do
         if books[j].shelf=s then anybookthere:=true;
end;

procedure savelib(where:string);
var lib:text;
begin
     assign(lib,where);
     rewrite(lib);
     for i:=1 to 10000 do
       begin
         if anybookthere(i) then writeln(lib,'shelf');
         for j:=1 to 10000 do
             if books[j].shelf=i then
                begin
                     writeln(lib,'book');
                     if books[j].author<>'-no author-' then
                        begin
                             writeln(lib,'author');
                             writeln(lib,books[j].author);
                        end;

                     if books[j].name<>'-no name-' then
                        begin
                             writeln(lib,'name');
                             writeln(lib,books[j].name);
                        end;
                     if books[j].editor<>'------------' then
                        begin
                             writeln(lib,'editor');
                             writeln(lib,books[j].editor);
                        end;
                     if books[j].outby<>'--' then
                        begin
                             writeln(lib,'outby');
                             writeln(lib,books[j].outby);
                        end;
                     if books[j].year<>'----' then
                        begin
                             writeln(lib,'year');
                             writeln(lib,books[j].year);
                        end;
                     if books[j].prize<>'-----' then
                        begin
                             writeln(lib,'prize');
                             writeln(lib,books[j].prize);
                        end;
                     if books[j].pages<>'-----' then
                        begin
                             writeln(lib,'pages');
                             writeln(lib,books[j].pages);
                        end;
                     if books[j].outt then
                        begin
                             writeln(lib,'out');
                        end;
                     if books[j].red then
                        begin
                             writeln(lib,'red');
                        end;
                     if books[j].reading then
                        begin
                             writeln(lib,'reading');
                        end;
                     if (books[j].datains.y<>'--')or(books[j].datains.m<>'--')or(books[j].datains.d<>'--') then
                        writeln(lib,'datains');
                     if books[j].datains.d<>'--' then writeln(lib,books[j].datains.d);
                     if books[j].datains.m<>'--' then writeln(lib,books[j].datains.m);
                     if books[j].datains.y<>'--' then writeln(lib,books[j].datains.y);
                end;
       end;
     close(lib);
end;

procedure writebookbox;
begin
     textcolor(lightgreen);
     gotoxy(68,3);
     write(books[selbook].name);
end;

procedure menu;
begin
    textcolor(lightgray);
    textbackground(black);
    clrscr;
    title;
    if part=2 then writebookbox;
    textcolor(lightgray);
    textbackground(black);
    sc:=1;
    textcolor(black);
    if keypressed then c:=readkey;
    if keypressed then c:=readkey;
    repeat
          k:=1;
          textbackground(lightgray);
          for i:=1 to 5 do
              begin
                   gotoxy(35,11+(i*2));
                   write(commands[i]);
              end;
          repeat
              k:=k+1;
              gotoxy(35,11+(sc*2));
              case sc of
                1: begin
                      if k mod 2=0 then  textbackground(yellow);
                      if k mod 2=1 then  textbackground(lightgray);
                   end;
                2: begin
                      if k mod 2=0 then  textbackground(yellow);
                      if k mod 2=1 then  textbackground(lightgray);
                   end;
                3: begin
                      if k mod 2=0 then  textbackground(yellow);
                      if k mod 2=1 then  textbackground(lightgray);
                   end;
                4: begin
                      if k mod 2=1 then  textbackground(lightgray);
                      if k mod 2=0 then
                         case part of
                              0: textbackground(yellow);
                              1: textbackground(yellow);
                              2: textbackground(red);
                         end;
                   end;
                5: begin
                      if k mod 2=1 then  textbackground(lightgray);
                      if k mod 2=0 then
                         case part of
                              0: textbackground(red);
                              1: textbackground(lightgreen);
                              2: textbackground(lightgreen);
                         end;
                    end;
              end;
              write(commands[sc]);
			  i:=0;
			  repeat
				delay(1);
				i:=i+1;
              until keypressed or (i=300);
          until keypressed;
          c:=readkey;
          if c=#0 then
             begin
                  c:=readkey;
                  case c of
                       #72:c:='w';
                       #80:c:='s';
                       #77:c:=' ';
                  end;
             end;
          if c=#13 then c:=' ';
          if c='w' then sc:=sc-1;
          if c='s' then sc:=sc+1;
          if c='a' then c:=' ';
          if sc=0 then sc:=5;
          if sc=6 then sc:=1;
    until c=' ';
end;

procedure caricamenu(ch:integer);
begin
case ch of
   0:
         begin
              commands[1]:='--visione generale--';
              commands[2]:='--ins. nuovo libro--';
              commands[3]:='----cerca libro-----';
              commands[4]:='--cambia  libreria--';
              commands[5]:='-------uscita-------';
         end;
   1:
        begin
              commands[1]:='--ricerca scaffale--';
              commands[2]:='---ricerca autore---';
              commands[3]:='---ricerca titolo---';
              commands[4]:='--ricerca data ins.-';
              commands[5]:='------indietro------';
        end;
   2:
        begin
              commands[1]:='---visione libro----';
              commands[2]:='--cambia attributi--';
              commands[3]:='----sposta libro----';
              commands[4]:='---cancella libro---';
              commands[5]:='------indietro------';
        end;
   end;
end;

procedure resetlist;
begin
     for j:=1 to 10000 do
         list[j]:=0;
end;

procedure listoptions;
begin
     textcolor(yellow);
     gotoxy(35,1);
     if part=0 then write('TUTTI I LIBRI')
               else
                 begin
                    write('RICERCA LIBRI');
                    gotoxy(1,3);
                    write('parametro di ricerca: "',request,'"');
                    case sc of
                         1:write(' - scaffale');
                         2:write(' - autore');
                         3:write(' - titolo');
                         4:write(' - data');
                    end;
                 end;
    gotoxy(40,3);
    textcolor(lightred);
    write('scelta: ');
    textcolor(yellow);
    repeat
          gotoxy(51,3);
          write('       ');
          gotoxy(51,3);
          readln(request);
    until isnum(request)or(request='b')or(request='q');
    if isnum(request)then
       begin
            part:=2;
            val(request,selbook,code);
       end;
end;

procedure showlist;
begin
     textbackground(blue);
     clrscr;
     textcolor(lightgreen);
     gotoxy(1,4);
     for i:=1 to 105+9 do
         write(chr(196));
     gotoxy(1,4);
     write(chr(218));
     gotoxy(7,4);
     write(chr(194));
     gotoxy(13,4);
     write(chr(194));
     gotoxy(16,4);
     write(chr(194));
     gotoxy(29,4);
     write(chr(194));
     gotoxy(50,4);
     write(chr(194));
     gotoxy(61,4);
     write(chr(194));
     gotoxy(66,4);
     write(chr(194));
     gotoxy(75,4);
     write(chr(194));
     gotoxy(79+5,4);
     write(chr(194));
     gotoxy(82+5,4);
     write(chr(194));
     gotoxy(88+5+1,4);
     write(chr(194));
     gotoxy(94+5+1,4);
     write(chr(194));
     gotoxy(98+5+1+2,4);
     write(chr(194));
     gotoxy(106+5+1+3,4);
     write(chr(191));
     gotoxy(1,5);
     writeln(chr(179),'     ',chr(179),' ID  ',chr(179),'sc',chr(179),'   autore   ',chr(179),'       titolo       ',chr(179),' edito da ',chr(179),'anno',chr(179),'aggiunto',chr(179),'prestato',chr(179),'a ',chr(179),'prezzo',chr(179),' pag ',chr(179),'letto',chr(179),'leggendo',chr(179));
     for i:=1 to 105+9 do
         write(chr(196));
     gotoxy(1,6);
     write(chr(195));
     gotoxy(7,6);
     write(chr(197));
     gotoxy(13,6);
     write(chr(197));
     gotoxy(16,6);
     write(chr(197));
     gotoxy(29,6);
     write(chr(197));
     gotoxy(50,6);
     write(chr(197));
     gotoxy(61,6);
     write(chr(197));
     gotoxy(66,6);
     write(chr(197));
     gotoxy(75,6);
     write(chr(197));
     gotoxy(79+5,6);
     write(chr(197));
     gotoxy(82+5,6);
     write(chr(197));
     gotoxy(88+6,6);
     write(chr(197));
     gotoxy(94+6,6);
     write(chr(197));
     gotoxy(98+8,6);
     write(chr(197));
     gotoxy(106+9,6);
     write(chr(180));
     i:=0;
     if list[1]<>0 then
        repeat
           i:=i+1;
           with books[list[i]] do
              begin
                 gotoxy(1,6+i);
                 write(chr(179),i);
                 gotoxy(7,6+i);
                 write(chr(179),list[i]);
                 gotoxy(13,6+i);
                 write(chr(179),shelf);
                 gotoxy(16,6+i);
                 write(chr(179),author);
                 gotoxy(29,6+i);
                 write(chr(179),name);
                 gotoxy(50,6+i);
                 write(chr(179),editor);
                 gotoxy(61,6+i);
                 write(chr(179),year);
                 gotoxy(66,6+i);
                 write(chr(179),datains.d,'/',datains.m,'/',datains.y);
                 gotoxy(75,6+i);
                 write(chr(179));
                 if outt then write('si')
                         else write('no');
                 gotoxy(79+5,6+i);
                 write(chr(179),outby);
                 gotoxy(82+5,6+i);
                 write(chr(179),prize);
                 gotoxy(88+6,6+i);
                 write(chr(179),pages);
                 gotoxy(94+6,6+i);
                 write(chr(179));
                 if red then write('si''')
                        else write('no ');
                 gotoxy(98+8,6+i);
                 write(chr(179));
                 if reading then write('   si''  ',chr(179))
                            else write('   no   ',chr(179));
              end;
        until (list[i+1]=0)or(i=10000);
     gotoxy(1,7+i);
     for i:=1 to 105+10 do
         write(chr(196));
     gotoxy(1,7+i);
     write(chr(192));
     gotoxy(7,7+i);
     write(chr(193));
     gotoxy(13,7+i);
     write(chr(193));
     gotoxy(16,7+i);
     write(chr(193));
     gotoxy(29,7+i);
     write(chr(193));
     gotoxy(50,7+i);
     write(chr(193));
     gotoxy(61,7+i);
     write(chr(193));
     gotoxy(66,7+i);
     write(chr(193));
     gotoxy(75,7+i);
     write(chr(193));
     gotoxy(79,7+i);
     write(chr(193));
     gotoxy(82,7+i);
     write(chr(193));
     gotoxy(88,7+i);
     write(chr(193));
     gotoxy(94,7+i);
     write(chr(193));
     gotoxy(98,7+i);
     write(chr(193));
     gotoxy(106,7+i);
     write(chr(217));
     gotoxy(1,1);
     if part<>2 then listoptions
                else repeat until keypressed;
end;

procedure ask(var req:string);
begin
     gotoxy(58,15);
     textcolor(yellow);
     textbackground(3);
     write('ricerca:');
     gotoxy(58,17);
     textcolor(lightgreen);
     readln(req);
     gotoxy(58,17);
     write('     ');
end;

procedure back;
begin
     part:=0;
end;

procedure viewall;
begin
     resetlist;
     j:=0;
     for i:=1 to 10000 do
       if books[i].shelf<>0 then 
         begin
              j:=j+1;
              list[j]:=i;
         end;
     showlist;
end;

procedure newbook;
begin
end;

procedure changelib;
begin
end;

procedure findbyshelf;
var intreq:integer;
begin
     resetlist;
     repeat
           ask(request);
     until isnum(request);
     val(request,intreq);
     j:=0;
     for i:=1 to 10000 do
         with books[i] do
              begin
                   if shelf=intreq then
                      begin
                           j:=j+1;
                           list[j]:=i;
                      end;
              end;
     showlist;
end;

procedure findbyauthor;
begin
     resetlist;
     repeat
           ask(request);
     until length(request)>0;
     j:=0;
     for i:=1 to 10000 do
         with books[i] do
              begin
                   if compare(author,request,length(request))and(books[i].shelf<>0) then
                      begin
                           j:=j+1;
                           list[j]:=i;
                      end;
              end;
     showlist;
end;

procedure findbyins;
var dd,mm,yy:string;
begin
     resetlist;
     gotoxy(58,14);
     repeat
           ask(dd);
     until isnum(dd);
     repeat
           ask(mm);
     until isnum(mm);
     repeat
           ask(yy);
     until isnum(yy);
     j:=0;
     for i:=1 to 10000 do
         with books[i] do
              begin
                   if (datains.d=dd)and(datains.m=mm)and(datains.y=yy)and(books[i].shelf<>0) then
                      begin
                           j:=j+1;
                           list[j]:=i;
                      end;
              end;
     for i:=1 to 10000 do
         with books[i] do
              begin
                   if (datains.m=mm)and(datains.y=yy)and(books[i].shelf<>0) then
                      begin
                           j:=j+1;
                           list[j]:=i;
                      end;
              end;
     for i:=1 to 10000 do
         with books[i] do
              begin
                   if (datains.y=yy)and(books[i].shelf<>0) then
                      begin
                           j:=j+1;
                           list[j]:=i;
                      end;
              end;
     showlist;
end;

procedure findbytitle;
begin
     resetlist;
     repeat
           ask(request);
     until length(request)>0;
     j:=0;
     for i:=1 to 10000 do
         with books[i] do
              begin
                   if compare(name,request,length(request))and(books[i].shelf<>0) then
                      begin
                           j:=j+1;
                           list[j]:=i;
                      end;
              end;
     showlist;
end;

procedure viewbook;
begin
     textbackground(blue);
     clrscr;
     textcolor(lightgreen);
     for i:=1 to 81 do
         for j:=1 to 25 do
             if ((i<=2)or(i>79)or(j<=2)or(j>23))and( ((i mod 2=1)and(j mod 2=0))or((i mod 2=0)and(j mod 2=1)) ) then
                begin
                     textbackground(red);
                     gotoxy(i,j);
                     write(' ');
                end
                else
                if ((i<=2)or(i>79)or(j<=2)or(j>23))then
                   begin
                        textbackground(green);
                        gotoxy(i,j);
                        write(' ');
                   end;
     gotoxy(1,1);
     for i:=3 to 79 do
         for j:=3 to 23 do
             if ((i mod 2=1)and(j mod 2=0))or((i mod 2=0)and(j mod 2=1)) then
                begin
                  gotoxy(i,j);
                  textbackground(0);
                  write(' ');
                end;
     with books[selbook] do
          begin
               textbackground(0);
               gotoxy(9,4);
               writeln('Titolo: ',name);
               gotoxy(9,7);
               writeln('Autore: ',author);
               gotoxy(9,10);
               writeln('Editore: ',editor);
               gotoxy(9,13);
               writeln('Anno: ',year);
               gotoxy(9,16);
               writeln('Pagine: ',pages);
               gotoxy(9,19);
               writeln('Prezzo: ',prize);
               gotoxy(45,4);
               writeln('Scaffale: ',shelf);
               gotoxy(45,7);
               write('Gia'' letto: ');
               if red then write('si''')
                      else write('no');
               gotoxy(45,10);
               write('In lettura: ');
               if reading then write('si''')
                          else write('no');
               gotoxy(45,13);
               write('Prestato: ');
               if outt then write('si''')
                       else write('no');
               gotoxy(45,16);
               writeln('Prestato a: ',outby);
               gotoxy(45,19);
               writeln('Data di inserimento: ',datains.d,'/',datains.m,'/',datains.y);
          end;
    gotoxy(20,22);
    textcolor(lightred);
    writeln('premere un tasto qualsiasi per tornare al menu''');
    repeat until keypressed;
end;

procedure movebook;
var newshelf:integer;
begin
     repeat
           gotoxy(58,15);
           textcolor(yellow);
           textbackground(3);
           write('nuovo scaffale:');
           gotoxy(58,17);
           textcolor(lightgreen);
           readln(request);
           gotoxy(58,17);
           write('     ');
     until isnum(request);
     val(request,newshelf);
     books[selbook].shelf:=newshelf;
end;

procedure modbook;
var newshelf:integer;
    newoutby,newname,newauthor,neweditor,newprize,newpages,newyear:string;
    newoutt,newnewred,newreading:boolean;
    newdatains:data;
begin
     textbackground(3);
     with books[selbook] do
        begin
           gotoxy(58,15);
           textcolor(yellow);
           write('cambiare scaffale?');
           repeat
{}               textcolor(lightgreen);
                 gotoxy(58,17);
                 readln(request);
                 gotoxy(58,17);
{}               write('     ');
           until (request='n')or(request='y');
           if request='y' then
              begin
{}                 gotoxy(58,11+4);
                   textcolor(blue);
{}                 write('cambia scaffale:');
{}                 gotoxy(58,13+4);
                   textcolor(lightred);
{}                 write('attuale: ',shelf);
{}                 gotoxy(58,15+4);
                   textcolor(yellow);
                   write('nuovo scaffale: ');
                   textcolor(lightgreen);
                   gotoxy(58,17+4);
                   write('     ');
                   gotoxy(58,17+4);
{}                 readln(newshelf);
              end;
//ALTRI PARAMETRI DA MODIFICARE

        end;
end;

procedure delbook;
begin
     gotoxy(58,15);
     textcolor(yellow);
     textbackground(3);
     write('delete? (y/n)');
     gotoxy(58,17);
     textcolor(lightgreen);
     readln(request);
     gotoxy(58,17);
     write('     ');
     if request='y' then books[selbook].shelf:=0;
     part:=0;
end;

procedure verifychoice;
begin
     case part of
          0:
            case sc of
                 1:viewall;
                 2:newbook;
                 3:part:=1;
                 4:changelib;
                 5:quitpar:=true;
            end;
          1:
            case sc of
                 1:findbyshelf;
                 2:findbyauthor;
                 3:findbytitle;
                 4:findbyins;
                 5:back;
            end;
          2:
            case sc of
                 1:viewbook;
                 2:modbook;
                 3:movebook;
                 4:delbook;
                 5:back;
            end;
     end;
end;

begin
     quitpar:=false;
     loadlib('f:\pas\libreria.ypl');
     repeat
           caricamenu(part);
           menu;
           verifychoice;
     until quitpar;
     textbackground(0);
     clrscr;
     textcolor(7);
     writeln('saving...');
     writeln;
     writeln('please wait');
     savelib('f:\pas\libreria.ypl');
end.
