program orcoboja;
uses crt;
var x,y:integer;
begin
writeln('dove la vuoi?');
readln(x,y);
textbackground(7);
clrscr;
textbackground(0);
gotoxy(0+x,0+y);
write(' ');
gotoxy(0+x,1+y);
write(' ');
gotoxy(0+x,2+y);
write(' ');
gotoxy(0+x,3+y);
write(' ');
gotoxy(0+x,4+y);
write(' ');
gotoxy(0+x,5+y);
write(' ');
gotoxy(0+x,6+y);
write(' ');
gotoxy(0+x,7+y);
write(' ');
gotoxy(0+x,8+y);
write(' ');
gotoxy(1+x,0+y);
write(' ');
gotoxy(1+x,1+y);
write(' ');
gotoxy(1+x,2+y);
write(' ');
gotoxy(1+x,3+y);
write(' ');
gotoxy(1+x,4+y);
write(' ');
gotoxy(1+x,5+y);
write(' ');
gotoxy(1+x,6+y);
write(' ');
gotoxy(1+x,7+y);
write(' ');
gotoxy(1+x,8+y);
write(' ');
gotoxy(2+x,0+y);
write(' ');
gotoxy(2+x,1+y);
write(' ');
gotoxy(2+x,4+y);
write(' ');
gotoxy(2+x,5+y);
write(' ');
gotoxy(3+x,0+y);
write(' ');
gotoxy(3+x,1+y);
write(' ');
gotoxy(3+x,4+y);
write(' ');
gotoxy(3+x,5+y);
write(' ');
gotoxy(4+x,0+y);
write(' ');
gotoxy(4+x,1+y);
write(' ');
gotoxy(4+x,2+y);
write(' ');
gotoxy(4+x,3+y);
write(' ');
gotoxy(4+x,4+y);
write(' ');
gotoxy(4+x,5+y);
write(' ');
gotoxy(4+x,6+y);
write(' ');
gotoxy(4+x,7+y);
write(' ');
gotoxy(4+x,8+y);
write(' ');
gotoxy(5+x,0+y);
write(' ');
gotoxy(5+x,1+y);
write(' ');
gotoxy(5+x,2+y);
write(' ');
gotoxy(5+x,3+y);
write(' ');
gotoxy(5+x,4+y);
write(' ');
gotoxy(5+x,5+y);
write(' ');
gotoxy(5+x,6+y);
write(' ');
gotoxy(5+x,7+y);
write(' ');
gotoxy(5+x,8+y);
write(' ');
readln;
end.
