program acpaint;
uses crt;
var x,j,k,y,i,mode,exmode,penna,dim,background_color,writing_color,letter_color:integer;
    c,letter:char;
    pixel:array[1..80]of array[1..24]of array[1..2]of integer;
    pixletter:array[1..80]of array[1..24]of char;
    bitmap:text;
    percorso:string;
    moment:boolean;
    commands:array[1..3]of string;

procedure title;
begin
           textbackground(white);
           clrscr;
gotoxy(12,2);
textbackground(0);
write(' ');
gotoxy(13,2);
write(' ');
gotoxy(14,2);
write(' ');
gotoxy(15,2);
write(' ');
gotoxy(16,2);
write(' ');
gotoxy(17,2);
write(' ');
gotoxy(18,2);
write(' ');
gotoxy(19,2);
write(' ');
gotoxy(20,2);
write(' ');
gotoxy(12,3);
textbackground(0);
write(' ');
gotoxy(13,3);
write(' ');
gotoxy(14,3);
write(' ');
gotoxy(15,3);
write(' ');
gotoxy(16,3);
write(' ');
gotoxy(17,3);
write(' ');
gotoxy(18,3);
write(' ');
gotoxy(19,3);
write(' ');
gotoxy(20,3);
write(' ');
gotoxy(21,3);
write(' ');
gotoxy(27,3);
textbackground(0);
write(' ');
gotoxy(28,3);
write(' ');
gotoxy(29,3);
write(' ');
gotoxy(30,3);
write(' ');
gotoxy(31,3);
write(' ');
gotoxy(36,3);
textbackground(0);
write(' ');
gotoxy(37,3);
write(' ');
gotoxy(41,3);
textbackground(0);
write(' ');
gotoxy(42,3);
write(' ');
gotoxy(43,3);
write(' ');
gotoxy(47,3);
textbackground(0);
write(' ');
gotoxy(48,3);
write(' ');
gotoxy(52,3);
textbackground(0);
write(' ');
gotoxy(53,3);
write(' ');
gotoxy(54,3);
write(' ');
gotoxy(55,3);
write(' ');
gotoxy(56,3);
write(' ');
gotoxy(57,3);
write(' ');
gotoxy(12,4);
textbackground(0);
write(' ');
gotoxy(13,4);
write(' ');
gotoxy(19,4);
textbackground(0);
write(' ');
gotoxy(20,4);
write(' ');
gotoxy(21,4);
write(' ');
gotoxy(22,4);
write(' ');
gotoxy(26,4);
textbackground(0);
write(' ');
gotoxy(27,4);
write(' ');
gotoxy(28,4);
write(' ');
gotoxy(29,4);
write(' ');
gotoxy(30,4);
write(' ');
gotoxy(31,4);
write(' ');
gotoxy(32,4);
write(' ');
gotoxy(36,4);
textbackground(0);
write(' ');
gotoxy(37,4);
write(' ');
gotoxy(41,4);
textbackground(0);
write(' ');
gotoxy(42,4);
write(' ');
gotoxy(43,4);
write(' ');
gotoxy(44,4);
write(' ');
gotoxy(47,4);
textbackground(0);
write(' ');
gotoxy(48,4);
write(' ');
gotoxy(52,4);
textbackground(0);
write(' ');
gotoxy(53,4);
write(' ');
gotoxy(54,4);
write(' ');
gotoxy(55,4);
write(' ');
gotoxy(56,4);
write(' ');
gotoxy(57,4);
write(' ');
gotoxy(12,5);
textbackground(0);
write(' ');
gotoxy(13,5);
write(' ');
gotoxy(20,5);
textbackground(0);
write(' ');
gotoxy(21,5);
write(' ');
gotoxy(22,5);
write(' ');
gotoxy(26,5);
textbackground(0);
write(' ');
gotoxy(27,5);
write(' ');
gotoxy(31,5);
textbackground(0);
write(' ');
gotoxy(32,5);
write(' ');
gotoxy(36,5);
textbackground(0);
write(' ');
gotoxy(37,5);
write(' ');
gotoxy(41,5);
textbackground(0);
write(' ');
gotoxy(42,5);
write(' ');
gotoxy(43,5);
write(' ');
gotoxy(44,5);
write(' ');
gotoxy(45,5);
write(' ');
gotoxy(47,5);
textbackground(0);
write(' ');
gotoxy(48,5);
write(' ');
gotoxy(54,5);
textbackground(0);
write(' ');
gotoxy(55,5);
write(' ');
gotoxy(12,6);
textbackground(0);
write(' ');
gotoxy(13,6);
write(' ');
gotoxy(20,6);
textbackground(0);
write(' ');
gotoxy(21,6);
write(' ');
gotoxy(22,6);
write(' ');
gotoxy(26,6);
textbackground(0);
write(' ');
gotoxy(27,6);
write(' ');
gotoxy(28,6);
write(' ');
gotoxy(29,6);
write(' ');
gotoxy(30,6);
write(' ');
gotoxy(31,6);
write(' ');
gotoxy(32,6);
write(' ');
gotoxy(36,6);
textbackground(0);
write(' ');
gotoxy(37,6);
write(' ');
gotoxy(41,6);
textbackground(0);
write(' ');
gotoxy(42,6);
write(' ');
gotoxy(44,6);
textbackground(0);
write(' ');
gotoxy(45,6);
write(' ');
gotoxy(46,6);
write(' ');
gotoxy(47,6);
write(' ');
gotoxy(48,6);
write(' ');
gotoxy(54,6);
textbackground(0);
write(' ');
gotoxy(55,6);
write(' ');
gotoxy(12,7);
textbackground(0);
write(' ');
gotoxy(13,7);
write(' ');
gotoxy(19,7);
textbackground(0);
write(' ');
gotoxy(20,7);
write(' ');
gotoxy(21,7);
write(' ');
gotoxy(22,7);
write(' ');
gotoxy(26,7);
textbackground(0);
write(' ');
gotoxy(27,7);
write(' ');
gotoxy(28,7);
write(' ');
gotoxy(29,7);
write(' ');
gotoxy(30,7);
write(' ');
gotoxy(31,7);
write(' ');
gotoxy(32,7);
write(' ');
gotoxy(36,7);
textbackground(0);
write(' ');
gotoxy(37,7);
write(' ');
gotoxy(41,7);
textbackground(0);
write(' ');
gotoxy(42,7);
write(' ');
gotoxy(45,7);
textbackground(0);
write(' ');
gotoxy(46,7);
write(' ');
gotoxy(47,7);
write(' ');
gotoxy(48,7);
write(' ');
gotoxy(54,7);
textbackground(0);
write(' ');
gotoxy(55,7);
write(' ');
gotoxy(12,8);
textbackground(0);
write(' ');
gotoxy(13,8);
write(' ');
gotoxy(14,8);
write(' ');
gotoxy(15,8);
write(' ');
gotoxy(16,8);
write(' ');
gotoxy(17,8);
write(' ');
gotoxy(18,8);
write(' ');
gotoxy(19,8);
write(' ');
gotoxy(20,8);
write(' ');
gotoxy(21,8);
write(' ');
gotoxy(26,8);
textbackground(0);
write(' ');
gotoxy(27,8);
write(' ');
gotoxy(31,8);
textbackground(0);
write(' ');
gotoxy(32,8);
write(' ');
gotoxy(36,8);
textbackground(0);
write(' ');
gotoxy(37,8);
write(' ');
gotoxy(41,8);
textbackground(0);
write(' ');
gotoxy(42,8);
write(' ');
gotoxy(46,8);
textbackground(0);
write(' ');
gotoxy(47,8);
write(' ');
gotoxy(48,8);
write(' ');
gotoxy(54,8);
textbackground(0);
write(' ');
gotoxy(55,8);
write(' ');
gotoxy(12,9);
textbackground(0);
write(' ');
gotoxy(13,9);
write(' ');
gotoxy(14,9);
write(' ');
gotoxy(15,9);
write(' ');
gotoxy(16,9);
write(' ');
gotoxy(17,9);
write(' ');
gotoxy(18,9);
write(' ');
gotoxy(19,9);
write(' ');
gotoxy(20,9);
write(' ');
gotoxy(26,9);
textbackground(0);
write(' ');
gotoxy(27,9);
write(' ');
gotoxy(31,9);
textbackground(0);
write(' ');
gotoxy(32,9);
write(' ');
gotoxy(36,9);
textbackground(0);
write(' ');
gotoxy(37,9);
write(' ');
gotoxy(41,9);
textbackground(0);
write(' ');
gotoxy(42,9);
write(' ');
gotoxy(47,9);
textbackground(0);
write(' ');
gotoxy(48,9);
write(' ');
gotoxy(54,9);
textbackground(0);
write(' ');
gotoxy(55,9);
write(' ');
gotoxy(12,10);
textbackground(0);
write(' ');
gotoxy(13,10);
write(' ');
gotoxy(12,11);
textbackground(0);
write(' ');
gotoxy(13,11);
write(' ');
gotoxy(15,11);
textbackground(2);
write(' ');
gotoxy(16,11);
write(' ');
gotoxy(18,11);
textbackground(2);
write(' ');
gotoxy(19,11);
write(' ');
gotoxy(21,11);
textbackground(2);
write(' ');
gotoxy(22,11);
write(' ');
gotoxy(23,11);
write(' ');
gotoxy(24,11);
write(' ');
gotoxy(25,11);
write(' ');
gotoxy(27,11);
textbackground(2);
write(' ');
gotoxy(28,11);
write(' ');
gotoxy(30,11);
textbackground(2);
write(' ');
gotoxy(31,11);
write(' ');
gotoxy(32,11);
write(' ');
gotoxy(52,11);
textbackground(4);
write(' ');
gotoxy(53,11);
write(' ');
gotoxy(54,11);
write(' ');
gotoxy(61,11);
textbackground(4);
write(' ');
gotoxy(62,11);
write(' ');
gotoxy(63,11);
write(' ');
gotoxy(65,11);
textbackground(4);
write(' ');
gotoxy(66,11);
write(' ');
gotoxy(67,11);
write(' ');
gotoxy(68,11);
write(' ');
gotoxy(69,11);
write(' ');
gotoxy(70,11);
write(' ');
gotoxy(71,11);
write(' ');
gotoxy(73,11);
textbackground(4);
write(' ');
gotoxy(74,11);
write(' ');
gotoxy(75,11);
write(' ');
gotoxy(76,11);
write(' ');
gotoxy(77,11);
write(' ');
gotoxy(78,11);
write(' ');
gotoxy(79,11);
write(' ');
gotoxy(12,12);
textbackground(0);
write(' ');
gotoxy(13,12);
write(' ');
gotoxy(15,12);
textbackground(2);
write(' ');
gotoxy(16,12);
write(' ');
gotoxy(18,12);
textbackground(2);
write(' ');
gotoxy(19,12);
write(' ');
gotoxy(21,12);
textbackground(2);
write(' ');
gotoxy(22,12);
write(' ');
gotoxy(23,12);
write(' ');
gotoxy(24,12);
write(' ');
gotoxy(25,12);
write(' ');
gotoxy(27,12);
textbackground(2);
write(' ');
gotoxy(28,12);
write(' ');
gotoxy(29,12);
write(' ');
gotoxy(30,12);
write(' ');
gotoxy(31,12);
write(' ');
gotoxy(32,12);
write(' ');
gotoxy(33,12);
write(' ');
gotoxy(52,12);
textbackground(4);
write(' ');
gotoxy(53,12);
write(' ');
gotoxy(54,12);
write(' ');
gotoxy(61,12);
textbackground(4);
write(' ');
gotoxy(62,12);
write(' ');
gotoxy(63,12);
write(' ');
gotoxy(65,12);
textbackground(4);
write(' ');
gotoxy(66,12);
write(' ');
gotoxy(67,12);
write(' ');
gotoxy(68,12);
write(' ');
gotoxy(69,12);
write(' ');
gotoxy(70,12);
write(' ');
gotoxy(71,12);
write(' ');
gotoxy(73,12);
textbackground(4);
write(' ');
gotoxy(74,12);
write(' ');
gotoxy(75,12);
write(' ');
gotoxy(76,12);
write(' ');
gotoxy(77,12);
write(' ');
gotoxy(78,12);
write(' ');
gotoxy(79,12);
write(' ');
gotoxy(12,13);
textbackground(0);
write(' ');
gotoxy(13,13);
write(' ');
gotoxy(15,13);
textbackground(2);
write(' ');
gotoxy(16,13);
write(' ');
gotoxy(18,13);
textbackground(2);
write(' ');
gotoxy(19,13);
write(' ');
gotoxy(21,13);
textbackground(2);
write(' ');
gotoxy(22,13);
write(' ');
gotoxy(24,13);
textbackground(2);
write(' ');
gotoxy(25,13);
write(' ');
gotoxy(27,13);
textbackground(2);
write(' ');
gotoxy(28,13);
write(' ');
gotoxy(29,13);
write(' ');
gotoxy(32,13);
textbackground(2);
write(' ');
gotoxy(33,13);
write(' ');
gotoxy(52,13);
textbackground(4);
write(' ');
gotoxy(53,13);
write(' ');
gotoxy(54,13);
write(' ');
gotoxy(65,13);
textbackground(4);
write(' ');
gotoxy(66,13);
write(' ');
gotoxy(67,13);
write(' ');
gotoxy(68,13);
write(' ');
gotoxy(69,13);
write(' ');
gotoxy(70,13);
write(' ');
gotoxy(71,13);
write(' ');
gotoxy(73,13);
textbackground(4);
write(' ');
gotoxy(74,13);
write(' ');
gotoxy(75,13);
write(' ');
gotoxy(76,13);
write(' ');
gotoxy(77,13);
write(' ');
gotoxy(78,13);
write(' ');
gotoxy(79,13);
write(' ');
gotoxy(12,14);
textbackground(0);
write(' ');
gotoxy(13,14);
write(' ');
gotoxy(15,14);
textbackground(2);
write(' ');
gotoxy(16,14);
write(' ');
gotoxy(17,14);
write(' ');
gotoxy(18,14);
write(' ');
gotoxy(19,14);
write(' ');
gotoxy(21,14);
textbackground(2);
write(' ');
gotoxy(22,14);
write(' ');
gotoxy(23,14);
write(' ');
gotoxy(24,14);
write(' ');
gotoxy(25,14);
write(' ');
gotoxy(27,14);
textbackground(2);
write(' ');
gotoxy(28,14);
write(' ');
gotoxy(52,14);
textbackground(4);
write(' ');
gotoxy(53,14);
write(' ');
gotoxy(54,14);
write(' ');
gotoxy(61,14);
textbackground(4);
write(' ');
gotoxy(62,14);
write(' ');
gotoxy(63,14);
write(' ');
gotoxy(65,14);
textbackground(4);
write(' ');
gotoxy(66,14);
write(' ');
gotoxy(67,14);
write(' ');
gotoxy(73,14);
textbackground(4);
write(' ');
gotoxy(74,14);
write(' ');
gotoxy(75,14);
write(' ');
gotoxy(12,15);
textbackground(0);
write(' ');
gotoxy(13,15);
write(' ');
gotoxy(15,15);
textbackground(2);
write(' ');
gotoxy(16,15);
write(' ');
gotoxy(17,15);
write(' ');
gotoxy(18,15);
write(' ');
gotoxy(19,15);
write(' ');
gotoxy(21,15);
textbackground(2);
write(' ');
gotoxy(22,15);
write(' ');
gotoxy(23,15);
write(' ');
gotoxy(24,15);
write(' ');
gotoxy(25,15);
write(' ');
gotoxy(27,15);
textbackground(2);
write(' ');
gotoxy(28,15);
write(' ');
gotoxy(52,15);
textbackground(4);
write(' ');
gotoxy(53,15);
write(' ');
gotoxy(54,15);
write(' ');
gotoxy(61,15);
textbackground(4);
write(' ');
gotoxy(62,15);
write(' ');
gotoxy(63,15);
write(' ');
gotoxy(65,15);
textbackground(4);
write(' ');
gotoxy(66,15);
write(' ');
gotoxy(67,15);
write(' ');
gotoxy(73,15);
textbackground(4);
write(' ');
gotoxy(74,15);
write(' ');
gotoxy(75,15);
write(' ');
gotoxy(12,16);
textbackground(0);
write(' ');
gotoxy(13,16);
write(' ');
gotoxy(18,16);
textbackground(2);
write(' ');
gotoxy(19,16);
write(' ');
gotoxy(27,16);
textbackground(2);
write(' ');
gotoxy(28,16);
write(' ');
gotoxy(52,16);
textbackground(4);
write(' ');
gotoxy(53,16);
write(' ');
gotoxy(54,16);
write(' ');
gotoxy(61,16);
textbackground(4);
write(' ');
gotoxy(62,16);
write(' ');
gotoxy(63,16);
write(' ');
gotoxy(65,16);
textbackground(4);
write(' ');
gotoxy(66,16);
write(' ');
gotoxy(67,16);
write(' ');
gotoxy(68,16);
write(' ');
gotoxy(69,16);
write(' ');
gotoxy(70,16);
write(' ');
gotoxy(73,16);
textbackground(4);
write(' ');
gotoxy(74,16);
write(' ');
gotoxy(75,16);
write(' ');
gotoxy(76,16);
write(' ');
gotoxy(77,16);
write(' ');
gotoxy(78,16);
write(' ');
gotoxy(12,17);
textbackground(0);
write(' ');
gotoxy(13,17);
write(' ');
gotoxy(18,17);
textbackground(2);
write(' ');
gotoxy(19,17);
write(' ');
gotoxy(21,17);
textbackground(2);
write(' ');
gotoxy(22,17);
write(' ');
gotoxy(24,17);
textbackground(2);
write(' ');
gotoxy(25,17);
write(' ');
gotoxy(27,17);
textbackground(2);
write(' ');
gotoxy(28,17);
write(' ');
gotoxy(52,17);
textbackground(4);
write(' ');
gotoxy(53,17);
write(' ');
gotoxy(54,17);
write(' ');
gotoxy(61,17);
textbackground(4);
write(' ');
gotoxy(62,17);
write(' ');
gotoxy(63,17);
write(' ');
gotoxy(65,17);
textbackground(4);
write(' ');
gotoxy(66,17);
write(' ');
gotoxy(67,17);
write(' ');
gotoxy(68,17);
write(' ');
gotoxy(69,17);
write(' ');
gotoxy(70,17);
write(' ');
gotoxy(73,17);
textbackground(4);
write(' ');
gotoxy(74,17);
write(' ');
gotoxy(75,17);
write(' ');
gotoxy(76,17);
write(' ');
gotoxy(77,17);
write(' ');
gotoxy(78,17);
write(' ');
gotoxy(12,18);
textbackground(0);
write(' ');
gotoxy(13,18);
write(' ');
gotoxy(18,18);
textbackground(2);
write(' ');
gotoxy(19,18);
write(' ');
gotoxy(21,18);
textbackground(2);
write(' ');
gotoxy(22,18);
write(' ');
gotoxy(24,18);
textbackground(2);
write(' ');
gotoxy(25,18);
write(' ');
gotoxy(27,18);
textbackground(2);
write(' ');
gotoxy(28,18);
write(' ');
gotoxy(52,18);
textbackground(4);
write(' ');
gotoxy(53,18);
write(' ');
gotoxy(54,18);
write(' ');
gotoxy(61,18);
textbackground(4);
write(' ');
gotoxy(62,18);
write(' ');
gotoxy(63,18);
write(' ');
gotoxy(65,18);
textbackground(4);
write(' ');
gotoxy(66,18);
write(' ');
gotoxy(67,18);
write(' ');
gotoxy(73,18);
textbackground(4);
write(' ');
gotoxy(74,18);
write(' ');
gotoxy(75,18);
write(' ');
gotoxy(12,19);
textbackground(0);
write(' ');
gotoxy(13,19);
write(' ');
gotoxy(15,19);
textbackground(2);
write(' ');
gotoxy(16,19);
write(' ');
gotoxy(18,19);
textbackground(2);
write(' ');
gotoxy(19,19);
write(' ');
gotoxy(21,19);
textbackground(2);
write(' ');
gotoxy(22,19);
write(' ');
gotoxy(24,19);
textbackground(2);
write(' ');
gotoxy(25,19);
write(' ');
gotoxy(27,19);
textbackground(2);
write(' ');
gotoxy(28,19);
write(' ');
gotoxy(52,19);
textbackground(4);
write(' ');
gotoxy(53,19);
write(' ');
gotoxy(54,19);
write(' ');
gotoxy(61,19);
textbackground(4);
write(' ');
gotoxy(62,19);
write(' ');
gotoxy(63,19);
write(' ');
gotoxy(65,19);
textbackground(4);
write(' ');
gotoxy(66,19);
write(' ');
gotoxy(67,19);
write(' ');
gotoxy(73,19);
textbackground(4);
write(' ');
gotoxy(74,19);
write(' ');
gotoxy(75,19);
write(' ');
gotoxy(12,20);
textbackground(0);
write(' ');
gotoxy(13,20);
write(' ');
gotoxy(15,20);
textbackground(2);
write(' ');
gotoxy(16,20);
write(' ');
gotoxy(18,20);
textbackground(2);
write(' ');
gotoxy(19,20);
write(' ');
gotoxy(21,20);
textbackground(2);
write(' ');
gotoxy(22,20);
write(' ');
gotoxy(24,20);
textbackground(2);
write(' ');
gotoxy(25,20);
write(' ');
gotoxy(27,20);
textbackground(2);
write(' ');
gotoxy(28,20);
write(' ');
gotoxy(52,20);
textbackground(4);
write(' ');
gotoxy(53,20);
write(' ');
gotoxy(54,20);
write(' ');
gotoxy(55,20);
write(' ');
gotoxy(56,20);
write(' ');
gotoxy(57,20);
write(' ');
gotoxy(58,20);
write(' ');
gotoxy(59,20);
write(' ');
gotoxy(61,20);
textbackground(4);
write(' ');
gotoxy(62,20);
write(' ');
gotoxy(63,20);
write(' ');
gotoxy(65,20);
textbackground(4);
write(' ');
gotoxy(66,20);
write(' ');
gotoxy(67,20);
write(' ');
gotoxy(73,20);
textbackground(4);
write(' ');
gotoxy(74,20);
write(' ');
gotoxy(75,20);
write(' ');
gotoxy(76,20);
write(' ');
gotoxy(77,20);
write(' ');
gotoxy(78,20);
write(' ');
gotoxy(79,20);
write(' ');
gotoxy(12,21);
textbackground(0);
write(' ');
gotoxy(13,21);
write(' ');
gotoxy(15,21);
textbackground(2);
write(' ');
gotoxy(16,21);
write(' ');
gotoxy(17,21);
write(' ');
gotoxy(18,21);
write(' ');
gotoxy(19,21);
write(' ');
gotoxy(21,21);
textbackground(2);
write(' ');
gotoxy(22,21);
write(' ');
gotoxy(23,21);
write(' ');
gotoxy(24,21);
write(' ');
gotoxy(25,21);
write(' ');
gotoxy(27,21);
textbackground(2);
write(' ');
gotoxy(28,21);
write(' ');
gotoxy(52,21);
textbackground(4);
write(' ');
gotoxy(53,21);
write(' ');
gotoxy(54,21);
write(' ');
gotoxy(55,21);
write(' ');
gotoxy(56,21);
write(' ');
gotoxy(57,21);
write(' ');
gotoxy(58,21);
write(' ');
gotoxy(59,21);
write(' ');
gotoxy(61,21);
textbackground(4);
write(' ');
gotoxy(62,21);
write(' ');
gotoxy(63,21);
write(' ');
gotoxy(65,21);
textbackground(4);
write(' ');
gotoxy(66,21);
write(' ');
gotoxy(67,21);
write(' ');
gotoxy(73,21);
textbackground(4);
write(' ');
gotoxy(74,21);
write(' ');
gotoxy(75,21);
write(' ');
gotoxy(76,21);
textcolor(4);
write(' ');
gotoxy(77,21);
textcolor(7);
write('');
gotoxy(78,21);
write(' ');
gotoxy(79,21);
write(' ');
gotoxy(12,22);
textbackground(0);
write(' ');
gotoxy(13,22);
write(' ');
gotoxy(15,22);
textbackground(2);
write(' ');
gotoxy(16,22);
write(' ');
gotoxy(17,22);
write(' ');
gotoxy(18,22);
write(' ');
gotoxy(19,22);
write(' ');
gotoxy(21,22);
textbackground(2);
write(' ');
gotoxy(22,22);
write(' ');
gotoxy(23,22);
write(' ');
gotoxy(24,22);
write(' ');
gotoxy(25,22);
write(' ');
gotoxy(27,22);
textbackground(2);
write(' ');
gotoxy(28,22);
write(' ');
gotoxy(52,22);
textbackground(4);
write(' ');
gotoxy(53,22);
write(' ');
gotoxy(54,22);
write(' ');
gotoxy(55,22);
write(' ');
gotoxy(56,22);
write(' ');
gotoxy(57,22);
write(' ');
gotoxy(58,22);
write(' ');
gotoxy(59,22);
write(' ');
gotoxy(61,22);
textbackground(4);
write(' ');
gotoxy(62,22);
write(' ');
gotoxy(63,22);
write(' ');
gotoxy(65,22);
textbackground(4);
write(' ');
gotoxy(66,22);
write(' ');
gotoxy(67,22);
write(' ');
gotoxy(73,22);
textbackground(4);
write(' ');
gotoxy(74,22);
write(' ');
gotoxy(75,22);
write(' ');
gotoxy(76,22);
write(' ');
gotoxy(77,22);
write(' ');
gotoxy(78,22);
write(' ');
gotoxy(79,22);
write(' ');
end;


procedure delall;
              begin
                textbackground(background_color);
                gotoxy(1,1);
                for i:=1 to 80*24 do write(' ');
                for i:=1 to 24 do
                  for k:=1 to 80 do pixel[k][i][1]:=background_color;
                for i:=1 to 24 do
                  for k:=1 to 80 do pixletter[k][i]:=' ';
                gotoxy(1,1);
              end;
procedure changebackground;
              begin
                gotoxy(60,25);
                for i:=1 to 10 do write('-');
                gotoxy(60,25);
                repeat
                  read(background_color);
                until (background_color<=7)and(background_color>=0);
                gotoxy(1,1);
              end;
procedure changeletter;
              begin
                gotoxy(13,25);
                readln(letter);
                gotoxy(1,1);
              end;
procedure changecolor(var color:integer);
begin
              repeat
                gotoxy(60,25);
                for i:=1 to 10 do write('-');
                gotoxy(60,25);
                read(color);
                gotoxy(1,1);
              until (color<=7)and(color>=0);
end;

procedure save;
begin
     rewrite(bitmap);
     for j:= 1 to 2 do
       for i:=1 to 24 do
         for k:=1 to 80 do writeln(bitmap,pixel[k][i][j]);
     for i:=1 to 24 do
       for k:=1 to 80 do writeln(bitmap,pixletter[k][i]);
     writeln(bitmap,background_color);
     close(bitmap);
end;

procedure load;
begin
        for j:=1 to 2 do
           for i:=1 to 24 do
               for k:=1 to 80 do readln(bitmap,pixel[k][i][j]);
        for i:=1 to 24 do
           for k:=1 to 80 do readln(bitmap,pixletter[k][i]);
        readln(bitmap,background_color);
end;


procedure caricamenu(mom:boolean);
begin
case mom of
   false:
         begin
              commands[1]:='----nuovo disegno---';
              commands[2]:='----apri disegno----';
              commands[3]:='---sessione libera--';
         end;
   true:
        begin
              commands[1]:='--------salva-------';
              commands[2]:='-----non salvare----';
        end;
   end;
end;

procedure riwrite;
begin
     for i:=1 to 24 do
       for k:=1 to 80 do pixel[k][i][1]:=7;
     for i:=1 to 24 do
       for k:=1 to 80 do pixel[k][i][2]:=0;
     for i:=1 to 24 do
       for k:=1 to 80 do pixletter[k][i]:=' ';
     background_color:=7;
end;

procedure initwrite;
begin
        for i:=1 to 24 do
           for k:=1 to 80  do
                  begin
                       gotoxy(k,i);
                       textbackground(pixel[k][i][1]);
                       textcolor(pixel[k][i][2]);
                       write(pixletter[k][i]);
                  end;
        gotoxy(1,25);
end;

procedure ask(check:boolean);
begin
     title;
        repeat
        textbackground(blue);
        textcolor(white);
        gotoxy(20,13);
        write(chr(201));
        for i:=1 to 38 do write(chr(205));
        write(chr(187));
        gotoxy(20,14);
        write(chr(186));
        gotoxy(59,14);
        write(chr(186));
        gotoxy(20,15);
        write(chr(200));
        for i:=1 to 38 do write(chr(205));
        write(chr(188));
        textcolor(white);
        if k=1 then
           begin
                gotoxy(21,14);
                write('file non trovato!');
                delay(1000);
           end;
        gotoxy(21,14);
        textbackground(blue);
        for i:=1 to 38 do write(' ');
        gotoxy(21,14);
        readln(percorso);
        percorso:=percorso+'.pyl';
        assign(bitmap,percorso);
        if check=true
           then
               {$I-}
               reset(bitmap)
               {$I+}
           else
               rewrite(bitmap);
        k:=1;
        until (IOResult=0)or(check=false);
end;

procedure neew;
begin
     ask(false);
     riwrite;
     save;
end;

procedure open;
begin
        ask(true);
        load;
end;

procedure verifychoice;
begin
     if moment=false then
        case mode of
             1:neew;
             2:open;
             3:riwrite;
        end
        else
        if mode=1 then
           if exmode=3 then
                       begin
                            ask(false);
                            save;
                       end
                       else save;
end;
procedure menu;
begin
    caricamenu(moment);
    textbackground(white);
    clrscr;
    title;
    textbackground(lightgray);
    textcolor(black);
    gotoxy(25,25);writeln('copyright (c) Alessandro Cacco 2011');
    gotoxy(1,1);
    mode:=1;
    textcolor(black);
    repeat
          k:=749;
          textbackground(black);
          textcolor(white);
          for i:=1 to 3 do
              if not((moment=true)and(i=3)) then
                  begin
                       gotoxy(31,13+(i*2));
                       write(commands[i]);
                  end;
          repeat
              k:=k+1;
              gotoxy(31,13+(mode*2));
              if k mod 1500=750 then  textbackground(blue);
              if k mod 1500=0 then  textbackground(0);
              write(commands[mode]);
          until keypressed;
          c:=readkey;
          if c='w' then mode:=mode-1;
          if c='s' then mode:=mode+1;
          case moment of
          false:
            begin
               if mode=0 then mode:=3;
               if mode=4 then mode:=1;
            end;
          true:
            begin
               if mode=3 then mode:=1;
               if mode=0 then mode:=2;
            end;
          end;
    until c=' ';
    verifychoice;
end;




begin
        menu;
        exmode:=mode;
        initwrite;
        textbackground(white);
        textcolor(black);
        for i:=1 to 80 do write('-');
        x:=1;
        y:=1;
        penna:=0;
        dim:=1;
        writing_color:=0;
        letter_color:=0;
        letter:=' ';
        repeat
        repeat
           if c='r' then delall;
           if c='b' then changebackground;
           textcolor(black);
           textbackground(white);
           gotoxy(1,25);
           write('carattere: ''');
           if c='l' then changeletter;
           gotoxy(13,25);
           write(letter,'''-----');
           if c='t' then changecolor(letter_color);
           if c='c' then changecolor(writing_color);
           gotoxy(60,25);
           write('----');
           gotoxy(53,25);
           write('colore: ',background_color,', ',writing_color,', ',letter_color);
           if (c='+')and(dim<6)and(x<81-dim)and(y<25-dim) then dim:=dim+1;
           if (c='-')and(dim>1) then dim:=dim-1;
           if c='p' then penna:=penna+1;
           if penna=3 then penna:=0;
           for i:=30 to 45 do
               begin
                    gotoxy(i,25);
                    write('-');
               end;
           gotoxy(20,25);
           write('cursore: ');
           gotoxy(29,25);
           if penna=0 then write('neutro');
           if penna=1 then write('pennarello - ',dim);
           if penna=2 then write('gomma - ',dim);
           gotoxy(x,y);
           c:=readkey;
           until (c='a')or(c='w')or(c='s')or(c='d')or(c='q');
        case c of
             'a': x:=x-1;
             's': y:=y+1;
             'd': x:=x+1;
             'w': y:=y-1;
        end;
        if x=0 then x:=81-dim;
        if x=82-dim then x:=1;
        if y=0 then y:=25-dim;
        if y=26-dim then y:=1;
        gotoxy(x,y);
        textcolor(letter_color);
        if penna=1 then textbackground(writing_color);
        if penna=2 then textbackground(background_color);
        if penna<>0 then
           for i:=y to y-1+dim do
               for k:=x to x-1+dim do
                  begin
                     gotoxy(k,i);
                     if penna=1 then write(letter)
                                else write(' ');
                     if penna=1 then
                        begin
                             pixel[k][i][1]:=writing_color;
                             pixel[k][i][2]:=letter_color;
                             pixletter[k][i]:=letter;
                        end
                        else
                        begin
                        pixel[k][i][1]:=background_color;
                        pixel[k][i][2]:=letter_color;
                        pixletter[k][i]:=' ';
                        end;
                  end;
        until c='q';
        moment:=true;
        caricamenu(moment);
        menu;
        verifychoice;
end.

