program acpaint;
uses crt,windows;
var x,j,k,y,i,penna,dim,background_color,writing_color,letter_color:integer;
    c,letter:char;
    pixel:array[1..80]of array[1..49]of array[1..2]of integer;
    pixletter:array[1..80]of array[1..49]of char;
    bitmap:text;
    percorso:string;
begin
repeat
textbackground(white);
clrscr;
gotoxy(12,2);
textbackground(0);
write(' ');
gotoxy(13,2);
write(' ');
gotoxy(14,2);
write(' ');
gotoxy(15,2);
write(' ');
gotoxy(16,2);
write(' ');
gotoxy(17,2);
write(' ');
gotoxy(18,2);
write(' ');
gotoxy(19,2);
write(' ');
gotoxy(20,2);
write(' ');
gotoxy(12,3);
textbackground(0);
write(' ');
gotoxy(13,3);
write(' ');
gotoxy(14,3);
write(' ');
gotoxy(15,3);
write(' ');
gotoxy(16,3);
write(' ');
gotoxy(17,3);
write(' ');
gotoxy(18,3);
write(' ');
gotoxy(19,3);
write(' ');
gotoxy(20,3);
write(' ');
gotoxy(21,3);
write(' ');
gotoxy(27,3);
textbackground(0);
write(' ');
gotoxy(28,3);
write(' ');
gotoxy(29,3);
write(' ');
gotoxy(30,3);
write(' ');
gotoxy(31,3);
write(' ');
gotoxy(36,3);
textbackground(0);
write(' ');
gotoxy(37,3);
write(' ');
gotoxy(41,3);
textbackground(0);
write(' ');
gotoxy(42,3);
write(' ');
gotoxy(43,3);
write(' ');
gotoxy(47,3);
textbackground(0);
write(' ');
gotoxy(48,3);
write(' ');
gotoxy(52,3);
textbackground(0);
write(' ');
gotoxy(53,3);
write(' ');
gotoxy(54,3);
write(' ');
gotoxy(55,3);
write(' ');
gotoxy(56,3);
write(' ');
gotoxy(57,3);
write(' ');
gotoxy(12,4);
textbackground(0);
write(' ');
gotoxy(13,4);
write(' ');
gotoxy(19,4);
textbackground(0);
write(' ');
gotoxy(20,4);
write(' ');
gotoxy(21,4);
write(' ');
gotoxy(22,4);
write(' ');
gotoxy(26,4);
textbackground(0);
write(' ');
gotoxy(27,4);
write(' ');
gotoxy(28,4);
write(' ');
gotoxy(29,4);
write(' ');
gotoxy(30,4);
write(' ');
gotoxy(31,4);
write(' ');
gotoxy(32,4);
write(' ');
gotoxy(36,4);
textbackground(0);
write(' ');
gotoxy(37,4);
write(' ');
gotoxy(41,4);
textbackground(0);
write(' ');
gotoxy(42,4);
write(' ');
gotoxy(43,4);
write(' ');
gotoxy(44,4);
write(' ');
gotoxy(47,4);
textbackground(0);
write(' ');
gotoxy(48,4);
write(' ');
gotoxy(52,4);
textbackground(0);
write(' ');
gotoxy(53,4);
write(' ');
gotoxy(54,4);
write(' ');
gotoxy(55,4);
write(' ');
gotoxy(56,4);
write(' ');
gotoxy(57,4);
write(' ');
gotoxy(12,5);
textbackground(0);
write(' ');
gotoxy(13,5);
write(' ');
gotoxy(20,5);
textbackground(0);
write(' ');
gotoxy(21,5);
write(' ');
gotoxy(22,5);
write(' ');
gotoxy(26,5);
textbackground(0);
write(' ');
gotoxy(27,5);
write(' ');
gotoxy(31,5);
textbackground(0);
write(' ');
gotoxy(32,5);
write(' ');
gotoxy(36,5);
textbackground(0);
write(' ');
gotoxy(37,5);
write(' ');
gotoxy(41,5);
textbackground(0);
write(' ');
gotoxy(42,5);
write(' ');
gotoxy(43,5);
write(' ');
gotoxy(44,5);
write(' ');
gotoxy(45,5);
write(' ');
gotoxy(47,5);
textbackground(0);
write(' ');
gotoxy(48,5);
write(' ');
gotoxy(54,5);
textbackground(0);
write(' ');
gotoxy(55,5);
write(' ');
gotoxy(12,6);
textbackground(0);
write(' ');
gotoxy(13,6);
write(' ');
gotoxy(20,6);
textbackground(0);
write(' ');
gotoxy(21,6);
write(' ');
gotoxy(22,6);
write(' ');
gotoxy(26,6);
textbackground(0);
write(' ');
gotoxy(27,6);
write(' ');
gotoxy(28,6);
write(' ');
gotoxy(29,6);
write(' ');
gotoxy(30,6);
write(' ');
gotoxy(31,6);
write(' ');
gotoxy(32,6);
write(' ');
gotoxy(36,6);
textbackground(0);
write(' ');
gotoxy(37,6);
write(' ');
gotoxy(41,6);
textbackground(0);
write(' ');
gotoxy(42,6);
write(' ');
gotoxy(44,6);
textbackground(0);
write(' ');
gotoxy(45,6);
write(' ');
gotoxy(46,6);
write(' ');
gotoxy(47,6);
write(' ');
gotoxy(48,6);
write(' ');
gotoxy(54,6);
textbackground(0);
write(' ');
gotoxy(55,6);
write(' ');
gotoxy(12,7);
textbackground(0);
write(' ');
gotoxy(13,7);
write(' ');
gotoxy(19,7);
textbackground(0);
write(' ');
gotoxy(20,7);
write(' ');
gotoxy(21,7);
write(' ');
gotoxy(22,7);
write(' ');
gotoxy(26,7);
textbackground(0);
write(' ');
gotoxy(27,7);
write(' ');
gotoxy(28,7);
write(' ');
gotoxy(29,7);
write(' ');
gotoxy(30,7);
write(' ');
gotoxy(31,7);
write(' ');
gotoxy(32,7);
write(' ');
gotoxy(36,7);
textbackground(0);
write(' ');
gotoxy(37,7);
write(' ');
gotoxy(41,7);
textbackground(0);
write(' ');
gotoxy(42,7);
write(' ');
gotoxy(45,7);
textbackground(0);
write(' ');
gotoxy(46,7);
write(' ');
gotoxy(47,7);
write(' ');
gotoxy(48,7);
write(' ');
gotoxy(54,7);
textbackground(0);
write(' ');
gotoxy(55,7);
write(' ');
gotoxy(12,8);
textbackground(0);
write(' ');
gotoxy(13,8);
write(' ');
gotoxy(14,8);
write(' ');
gotoxy(15,8);
write(' ');
gotoxy(16,8);
write(' ');
gotoxy(17,8);
write(' ');
gotoxy(18,8);
write(' ');
gotoxy(19,8);
write(' ');
gotoxy(20,8);
write(' ');
gotoxy(21,8);
write(' ');
gotoxy(26,8);
textbackground(0);
write(' ');
gotoxy(27,8);
write(' ');
gotoxy(31,8);
textbackground(0);
write(' ');
gotoxy(32,8);
write(' ');
gotoxy(36,8);
textbackground(0);
write(' ');
gotoxy(37,8);
write(' ');
gotoxy(41,8);
textbackground(0);
write(' ');
gotoxy(42,8);
write(' ');
gotoxy(46,8);
textbackground(0);
write(' ');
gotoxy(47,8);
write(' ');
gotoxy(48,8);
write(' ');
gotoxy(54,8);
textbackground(0);
write(' ');
gotoxy(55,8);
write(' ');
gotoxy(12,9);
textbackground(0);
write(' ');
gotoxy(13,9);
write(' ');
gotoxy(14,9);
write(' ');
gotoxy(15,9);
write(' ');
gotoxy(16,9);
write(' ');
gotoxy(17,9);
write(' ');
gotoxy(18,9);
write(' ');
gotoxy(19,9);
write(' ');
gotoxy(20,9);
write(' ');
gotoxy(26,9);
textbackground(0);
write(' ');
gotoxy(27,9);
write(' ');
gotoxy(31,9);
textbackground(0);
write(' ');
gotoxy(32,9);
write(' ');
gotoxy(36,9);
textbackground(0);
write(' ');
gotoxy(37,9);
write(' ');
gotoxy(41,9);
textbackground(0);
write(' ');
gotoxy(42,9);
write(' ');
gotoxy(47,9);
textbackground(0);
write(' ');
gotoxy(48,9);
write(' ');
gotoxy(54,9);
textbackground(0);
write(' ');
gotoxy(55,9);
write(' ');
gotoxy(12,10);
textbackground(0);
write(' ');
gotoxy(13,10);
write(' ');
gotoxy(12,11);
textbackground(0);
write(' ');
gotoxy(13,11);
write(' ');
gotoxy(12,12);
textbackground(0);
write(' ');
gotoxy(13,12);
write(' ');
gotoxy(12,13);
textbackground(0);
write(' ');
gotoxy(13,13);
write(' ');
gotoxy(12,14);
textbackground(0);
write(' ');
gotoxy(13,14);
write(' ');
gotoxy(12,15);
textbackground(0);
write(' ');
gotoxy(13,15);
write(' ');
gotoxy(12,16);
textbackground(0);
write(' ');
gotoxy(13,16);
write(' ');
gotoxy(12,17);
textbackground(0);
write(' ');
gotoxy(13,17);
write(' ');
gotoxy(12,18);
textbackground(0);
write(' ');
gotoxy(13,18);
write(' ');
gotoxy(21,18);
textbackground(2);
write(' ');
gotoxy(23,18);
textbackground(2);
write(' ');
gotoxy(25,18);
textbackground(2);
write(' ');
gotoxy(26,18);
write(' ');
gotoxy(27,18);
write(' ');
gotoxy(29,18);
textbackground(2);
write(' ');
gotoxy(31,18);
textbackground(2);
write(' ');
gotoxy(33,18);
textbackground(2);
write(' ');
gotoxy(35,18);
textbackground(2);
write(' ');
gotoxy(41,18);
textbackground(4);
write(' ');
gotoxy(42,18);
write(' ');
gotoxy(48,18);
textbackground(4);
write(' ');
gotoxy(49,18);
write(' ');
gotoxy(12,19);
textbackground(0);
write(' ');
gotoxy(13,19);
write(' ');
gotoxy(21,19);
textbackground(2);
write(' ');
gotoxy(23,19);
textbackground(2);
write(' ');
gotoxy(25,19);
textbackground(2);
write(' ');
gotoxy(27,19);
textbackground(2);
write(' ');
gotoxy(29,19);
textbackground(2);
write(' ');
gotoxy(31,19);
textbackground(2);
write(' ');
gotoxy(33,19);
textbackground(2);
write(' ');
gotoxy(34,19);
write(' ');
gotoxy(41,19);
textbackground(4);
write(' ');
gotoxy(42,19);
write(' ');
gotoxy(52,19);
textbackground(4);
write(' ');
gotoxy(53,19);
write(' ');
gotoxy(54,19);
write(' ');
gotoxy(55,19);
write(' ');
gotoxy(58,19);
textbackground(4);
write(' ');
gotoxy(59,19);
write(' ');
gotoxy(60,19);
write(' ');
gotoxy(61,19);
write(' ');
gotoxy(12,20);
textbackground(0);
write(' ');
gotoxy(13,20);
write(' ');
gotoxy(21,20);
textbackground(2);
write(' ');
gotoxy(22,20);
write(' ');
gotoxy(23,20);
write(' ');
gotoxy(25,20);
textbackground(2);
write(' ');
gotoxy(26,20);
write(' ');
gotoxy(27,20);
write(' ');
gotoxy(29,20);
textbackground(2);
write(' ');
gotoxy(30,20);
write(' ');
gotoxy(31,20);
write(' ');
gotoxy(33,20);
textbackground(2);
write(' ');
gotoxy(41,20);
textbackground(4);
write(' ');
gotoxy(42,20);
write(' ');
gotoxy(48,20);
textbackground(4);
write(' ');
gotoxy(49,20);
write(' ');
gotoxy(52,20);
textbackground(4);
write(' ');
gotoxy(53,20);
write(' ');
gotoxy(58,20);
textbackground(4);
write(' ');
gotoxy(59,20);
write(' ');
gotoxy(12,21);
textbackground(0);
write(' ');
gotoxy(13,21);
write(' ');
gotoxy(23,21);
textbackground(2);
write(' ');
gotoxy(41,21);
textbackground(4);
write(' ');
gotoxy(42,21);
write(' ');
gotoxy(48,21);
textbackground(4);
write(' ');
gotoxy(49,21);
write(' ');
gotoxy(52,21);
textbackground(4);
write(' ');
gotoxy(53,21);
write(' ');
gotoxy(54,21);
write(' ');
gotoxy(58,21);
textbackground(4);
write(' ');
gotoxy(59,21);
write(' ');
gotoxy(60,21);
write(' ');
gotoxy(12,22);
textbackground(0);
write(' ');
gotoxy(13,22);
write(' ');
gotoxy(21,22);
textbackground(2);
write(' ');
gotoxy(23,22);
textbackground(2);
write(' ');
gotoxy(41,22);
textbackground(4);
write(' ');
gotoxy(42,22);
write(' ');
gotoxy(43,22);
write(' ');
gotoxy(44,22);
write(' ');
gotoxy(45,22);
write(' ');
gotoxy(48,22);
textbackground(4);
write(' ');
gotoxy(49,22);
write(' ');
gotoxy(52,22);
textbackground(4);
write(' ');
gotoxy(53,22);
write(' ');
gotoxy(58,22);
textbackground(4);
write(' ');
gotoxy(59,22);
write(' ');
gotoxy(21,23);
textbackground(2);
write(' ');
gotoxy(22,23);
write(' ');
gotoxy(23,23);
write(' ');
gotoxy(41,23);
textbackground(4);
write(' ');
gotoxy(42,23);
write(' ');
gotoxy(43,23);
write(' ');
gotoxy(44,23);
write(' ');
gotoxy(45,23);
write(' ');
gotoxy(48,23);
textbackground(4);
write(' ');
gotoxy(49,23);
write(' ');
gotoxy(52,23);
textbackground(4);
write(' ');
gotoxy(53,23);
write(' ');
gotoxy(58,23);
textbackground(4);
write(' ');
gotoxy(59,23);
write(' ');
gotoxy(60,23);
write(' ');
gotoxy(61,23);
write(' ');
        textbackground(white);
        textbackground(red);
        textcolor(white);
        gotoxy(20,13);
        write(chr(201));
        for i:=1 to 38 do write(chr(205));
        write(chr(187));
        gotoxy(20,14);
        write(chr(186));
        gotoxy(59,14);
        write(chr(186));
        gotoxy(20,15);
        write(chr(200));
        for i:=1 to 38 do write(chr(205));
        write(chr(188));
        textcolor(white);
        if k=1 then
           begin
                gotoxy(21,14);
                write('file non trovato!                     ');
                delay(1000);
           end;
        gotoxy(21,14);
        textbackground(red);
        for i:=1 to 38 do write(' ');
        gotoxy(21,14);
        readln(percorso);
        percorso:=percorso+'.pylfs';
        assign(bitmap,percorso);
        {$I-}
        reset(bitmap);
        {$I+}
        k:=1;
        until IOResult=0;
        for j:=1 to 2 do
           for i:=1 to 49 do
               for k:=1 to 80 do readln(bitmap,pixel[k][i][j]);
        for i:=1 to 49 do
           for k:=1 to 80 do readln(bitmap,pixletter[k][i]);
        readln(bitmap,background_color);
        textbackground(7);
        clrscr;
        keybd_event(VK_MENU,56,0,0);
        keybd_event(VK_RETURN,28,0,0);
        keybd_event(VK_MENU,56,KEYEVENTF_KEYUP,0);
        keybd_event(VK_RETURN,28,KEYEVENTF_KEYUP,0);
        for i:=1 to 49 do
           for k:=1 to 80  do
                  begin
                       gotoxy(k,i);
                       textbackground(pixel[k][i][1]);
                       textcolor(pixel[k][i][2]);
                       write(pixletter[k][i]);
                  end;
        gotoxy(1,50);
        textbackground(white);
        textcolor(black);
        for i:=1 to 80 do write('-');
        x:=1;
        y:=1;
        penna:=0;
        dim:=1;
        writing_color:=0;
        letter_color:=0;
        letter:=' ';
        repeat
        repeat
           if c='r' then
              begin
                textbackground(background_color);
                gotoxy(1,1);
                for i:=1 to 80*49 do write(' ');
                for i:=1 to 49 do
                  for k:=1 to 80 do pixel[k][i][1]:=background_color;
                for i:=1 to 49 do
                  for k:=1 to 80 do pixletter[k][i]:=' ';
                gotoxy(1,1);
              end;
           if c='b' then
              begin
                gotoxy(60,50);
                for i:=1 to 10 do write('-');
                gotoxy(60,50);
                repeat
                  read(background_color);
                until (background_color<=7)and(background_color>=0);
                gotoxy(1,1);
              end;
           textcolor(black);
           textbackground(white);
           gotoxy(1,50);
           write('carattere: ''');
           if c='l' then
              begin
                gotoxy(13,50);
                readln(letter);
                gotoxy(1,1);
              end;
           gotoxy(13,50);
           write(letter,'''-----');
           if c='t' then
              repeat
                gotoxy(60,50);
                for i:=1 to 10 do write('-');
                gotoxy(60,50);
                read(letter_color);
                gotoxy(1,1);
              until (letter_color<=7)and(writing_color>=0);
           if c='c' then
              repeat
                      gotoxy(60,50);
                      for i:=1 to 10 do write('-');
                      gotoxy(60,50);
                      read(writing_color);
                      gotoxy(1,1);
              until (writing_color<=7)and(writing_color>=0);
           gotoxy(60,50);
           write('----');
           gotoxy(53,50);
           write('colore: ',background_color,', ',writing_color,', ',letter_color);
           if (c='+')and(dim<6)and(x<81-dim)and(y<50-dim) then dim:=dim+1;
           if (c='-')and(dim>1) then dim:=dim-1;
           if c='p' then penna:=penna+1;
           if penna=3 then penna:=0;
           for i:=30 to 45 do
               begin
                    gotoxy(i,50);
                    write('-');
               end;
           gotoxy(20,50);
           write('cursore: ');
           gotoxy(29,50);
           if penna=0 then write('neutro');
           if penna=1 then write('pennarello - ',dim);
           if penna=2 then write('gomma - ',dim);
           gotoxy(x,y);
           c:=readkey;
           until (c='a')or(c='w')or(c='s')or(c='d')or(c='q');
        if c='a' then x:=x-1;
        if c='s' then y:=y+1;
        if c='d' then x:=x+1;
        if c='w' then y:=y-1;
        if x=0 then x:=81-dim;
        if x=82-dim then x:=1;
        if y=0 then y:=50-dim;
        if y=51-dim then y:=1;
        gotoxy(x,y);
        textcolor(letter_color);
        if penna=1 then textbackground(writing_color);
        if penna=2 then textbackground(background_color);
        if penna<>0 then
           for i:=y to y-1+dim do
               for k:=x to x-1+dim do
                  begin
                     gotoxy(k,i);
                     if penna=1 then write(letter)
                                else write(' ');
                     if penna=1 then
                        begin
                             pixel[k][i][1]:=writing_color;
                             pixel[k][i][2]:=letter_color;
                             pixletter[k][i]:=letter;
                        end
                        else
                        begin
                        pixel[k][i][1]:=background_color;
                        pixel[k][i][2]:=letter_color;
                        pixletter[k][i]:=' ';
                        end;
                  end;
     until (c='q');
     rewrite(bitmap);
     for j:= 1 to 2 do
       for i:=1 to 49 do
         for k:=1 to 80 do writeln(bitmap,pixel[k][i][j]);
     for i:=1 to 49 do
       for k:=1 to 80 do writeln(bitmap,pixletter[k][i]);
     writeln(bitmap,background_color);
     close(bitmap);
end.

