(*questa è una versione incompleta del mio programma Paint Your Life.
questa versione si sarebbe dovuta basare su dei menù contestuali, ma
per scarso e nessuna necessita di questi non è mai stato portato a termine.
nessuno tranne il sottoscritto lo sa utilizzare per creare titoli per programmi pascal,
motivo per cui non sono necessarie ulteriori semplificazioni, che sarebbero
un inutile perdita di tempo per l'utilizzo che l'unico utente, io, ne farebbe.
tristemente, dichiaro che oggi questo programma è un abandonware,

Alessandro Cacco, 14/9/2013*)
program acpaint;
uses crt;
const larghezza=80;
      altezza=50;
var x,j,k,y,i,penna,dim,background_color,writing_color,letter_color:integer;
    c,letter:char;
    pixel:array[1..80]of array[1..24]of array[1..2]of integer;
    pixletter:array[1..80]of array[1..24]of char;
    bitmap:text;
    percorso:string;
procedure comandi;
var largh,high,xa:integer;
    elenco:array[1..3]of array[1..5] of string[12];
begin
        textcolor(7);
        textbackground(blue);
        x:=1;
        y:=1;
        gotoxy(x,y);
        write('| file ||  disegno   || aiuto  |');
        i:=1;
        elenco[1][1]:='salva';
        elenco[1][2]:='chiudi';
        elenco[1][3]:='esci';
        elenco[1][4]:='0';
        elenco[1][5]:='0';
        elenco[2][1]:='col. sfondo';
        elenco[2][2]:='col. lettera';
        elenco[2][3]:='col. pixel';
        elenco[2][4]:='lettera';
        elenco[2][5]:='canc. tutto!';
        elenco[3][1]:='aiuto!';
        elenco[3][2]:='info';
        elenco[3][3]:='0';
        elenco[3][4]:='0';
        elenco[3][5]:='0';
        repeat
            for i:=2 to 24 do
              for k:=1 to 80 do
                begin
                  gotoxy(k,i);
                  textbackground(pixel[k][i][1]);
                  textcolor(pixel[k][i][2]);
                  write(pixletter[k][i]);
                end;
            textcolor(7);
            textbackground(blue);
            repeat
              c:=readkey;
              if c='a' then x:=x-1;
              if c='d' then x:=x+1;
              if x=4 then x:=1;
              if x=0 then x:=3;
              i:=0;
              if (x=1)and(y=1) then
                  repeat
                  i:=i+1;
                  delay(200);
                  gotoxy(1,1);
                  if i mod 2=0 then write('*')
                               else write('|');
                  until keypressed;
              if (x=2)and(y=1) then
                  repeat
                  i:=i+1;
                  delay(200);
                  gotoxy(9,1);
                  if i mod 2=0 then write('*')
                               else write('|');
                  until keypressed;
              if (x=3)and(y=1) then
                  repeat
                  i:=i+1;
                  delay(200);
                  gotoxy(23,1);
                  if i mod 2=0 then write('*')
                               else write('|');
                  until keypressed;

            until (c='s');
            if x=1 then
              begin
                largh:=6;
                high:=3;
                xa:=1;
              end;
            if x=2 then
              begin
                largh:=12;
                high:=5;
                xa:=9;
              end;
            if x=3 then
              begin
                largh:=8;
                high:=2;
                xa:=22;
              end;
            gotoxy(xa,2);
            write(chr(218));
            for i:=1 to largh  do write(chr(196));
            write(chr(191));
            gotoxy(xa,high+3);
            write(chr(192));
            for i:=1 to largh do write(chr(196));
            write(chr(217));
            for i:=3 to high+2 do
                begin
                     gotoxy(xa,i);
                     write(chr(179));
                     gotoxy(xa+1+largh,i);
                     write(chr(179));
                     end;
            for i:=3 to 7 do
                begin
                     gotoxy(xa+1,i);
                     if elenco[x][i-2]<>'0' then write(elenco[x][i-2]);
                end;
            c:=readkey;
        until c=' ';
        for i:=1 to 24 do
            for k:=1 to 80 do
                begin
                     gotoxy(k,i);
                     textbackground(pixel[k][i][1]);
                     textcolor(pixel[k][i][2]);
                     write(pixletter[k][i]);
                end;
        if c='r' then
              begin
                   textbackground(background_color);
                   gotoxy(40,1); gotoxy(1,2);
                   for i:=1 to 80*24 do write(' ');
                   for i:=1 to 24 do
                       for k:=1 to 80 do pixel[k][i][1]:=background_color;
                   for i:=1 to 24 do
                       for k:=1 to 80 do pixletter[k][i]:=' ';
                   gotoxy(40,1); gotoxy(1,2);
              end;
        if c='b' then
              begin
                   gotoxy(60,25);
                   for i:=1 to 10 do write('-');
                   gotoxy(60,25);
                   repeat
                         read(background_color);
                   until (background_color<=7)and(background_color>=0);
                   gotoxy(40,1); gotoxy(1,2);
              end;
        if c='l' then
              begin
                   gotoxy(13,25);
                   readln(letter);
                   gotoxy(40,1); gotoxy(1,2);
              end;
        if c='t' then
              repeat
                   gotoxy(60,25);
                   for i:=1 to 10 do write('-');
                   gotoxy(60,25);
                   read(letter_color);
                   gotoxy(40,1); gotoxy(1,2);
              until (letter_color<=7)and(writing_color>=0);
        if c='c' then
              repeat
                   gotoxy(60,25);
                   for i:=1 to 10 do write('-');
                   gotoxy(60,25);
                   read(writing_color);
                   gotoxy(40,1); gotoxy(1,2);
              until (writing_color<=7)and(writing_color>=0);
        gotoxy(40,1); gotoxy(1,2);
end;
begin
        textbackground(white);
        clrscr;
        gotoxy(12,2);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(13,2);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(14,2);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(15,2);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(16,2);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(17,2);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(18,2);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(19,2);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(20,2);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(12,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(13,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(14,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(15,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(16,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(17,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(18,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(19,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(20,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(21,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(27,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(28,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(29,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(30,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(31,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(36,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(37,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(41,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(42,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(43,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(47,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(48,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(52,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(53,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(54,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(55,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(56,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(57,3);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(12,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(13,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(19,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(20,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(21,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(22,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(26,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(27,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(28,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(29,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(30,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(31,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(32,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(36,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(37,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(41,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(42,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(43,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(44,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(47,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(48,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(52,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(53,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(54,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(55,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(56,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(57,4);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(12,5);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(13,5);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(20,5);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(21,5);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(22,5);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(26,5);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(27,5);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(31,5);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(32,5);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(36,5);
        textbackground(0);
        textcolor(0);
        write(' ');
        gotoxy(37,5);
        textbackground(0);
        textcolor(0);
        write(' ');
gotoxy(41,5);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(42,5);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(43,5);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(44,5);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(45,5);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(47,5);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(48,5);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(54,5);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(55,5);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(12,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(20,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(21,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(22,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(26,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(27,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(28,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(29,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(30,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(31,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(32,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(36,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(37,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(41,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(42,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(44,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(45,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(46,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(47,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(48,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(54,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(55,6);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(12,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(19,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(20,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(21,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(22,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(26,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(27,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(28,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(29,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(30,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(31,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(32,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(36,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(37,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(41,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(42,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(45,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(46,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(47,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(48,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(54,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(55,7);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(12,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(14,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(15,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(16,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(17,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(18,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(19,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(20,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(21,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(26,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(27,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(31,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(32,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(36,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(37,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(41,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(42,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(46,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(47,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(48,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(54,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(55,8);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(12,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(14,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(15,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(16,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(17,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(18,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(19,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(20,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(26,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(27,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(31,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(32,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(36,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(37,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(41,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(42,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(47,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(48,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(54,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(55,9);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(12,10);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,10);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(12,11);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,11);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(12,12);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,12);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(12,13);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,13);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(12,14);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,14);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(12,15);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,15);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(12,16);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,16);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(12,17);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,17);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(12,18);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,18);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(21,18);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(23,18);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(25,18);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(26,18);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(27,18);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(29,18);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(31,18);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(33,18);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(35,18);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(41,18);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(42,18);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(48,18);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(49,18);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(12,19);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,19);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(21,19);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(23,19);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(25,19);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(27,19);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(29,19);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(31,19);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(33,19);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(34,19);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(41,19);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(42,19);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(52,19);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(53,19);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(54,19);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(55,19);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(58,19);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(59,19);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(60,19);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(61,19);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(12,20);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,20);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(21,20);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(22,20);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(23,20);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(25,20);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(26,20);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(27,20);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(29,20);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(30,20);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(31,20);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(33,20);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(41,20);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(42,20);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(48,20);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(49,20);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(52,20);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(53,20);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(58,20);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(59,20);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(12,21);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,21);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(23,21);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(41,21);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(42,21);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(48,21);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(49,21);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(52,21);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(53,21);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(54,21);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(58,21);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(59,21);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(60,21);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(12,22);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(13,22);
textbackground(0);
textcolor(0);
write(' ');
gotoxy(21,22);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(23,22);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(41,22);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(42,22);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(43,22);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(44,22);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(45,22);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(48,22);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(49,22);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(52,22);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(53,22);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(58,22);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(59,22);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(21,23);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(22,23);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(23,23);
textbackground(2);
textcolor(0);
write(' ');
gotoxy(41,23);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(42,23);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(43,23);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(44,23);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(45,23);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(48,23);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(49,23);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(52,23);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(53,23);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(58,23);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(59,23);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(60,23);
textbackground(4);
textcolor(0);
write(' ');
gotoxy(61,23);
textbackground(4);
textcolor(0);
write(' ');
        textbackground(white);
        textbackground(red);
        textcolor(white);
        gotoxy(20,13);
        write(chr(201));
        for i:=1 to 38 do write(chr(205));
        write(chr(187));
        gotoxy(20,14);
        write(chr(186));
        gotoxy(59,14);
        write(chr(186));
        gotoxy(20,15);
        write(chr(200));
        for i:=1 to 38 do write(chr(205));
        write(chr(188));
        gotoxy(21,14);
        read(percorso);
        //percorso:='N:\pas\disegno';
        percorso:=percorso+'.pyl';
        assign(bitmap,percorso);
        reset(bitmap);
        for j:=1 to 2 do
           for i:=1 to 24 do
               for k:=1 to 80 do readln(bitmap,pixel[k][i][j]);
        for i:=1 to 24 do
           for k:=1 to 80 do readln(bitmap,pixletter[k][i]);
        readln(bitmap,background_color);
        for i:=1 to 24 do
           for k:=1 to 80  do
                  begin
                       gotoxy(k,i);
                       textbackground(pixel[k][i][1]);
                       textcolor(pixel[k][i][2]);
                       write(pixletter[k][i]);
                  end;
        gotoxy(1,25);
        textbackground(white);
        textcolor(black);
        for i:=1 to 80 do write('-');
        x:=1;
        y:=2;
        penna:=0;
        dim:=1;
        writing_color:=0;
        letter_color:=0;
        letter:=' ';
        repeat
        repeat
           if c='j'then comandi;
           textcolor(black);
           textbackground(white);
           gotoxy(1,25);
           write('carattere: ''');
           gotoxy(13,25);
           write(letter,'''-----');
           gotoxy(60,25);
           write('----');
           gotoxy(53,25);
           write('colore: ',background_color,', ',writing_color,', ',letter_color);
           if (c='+')and(dim<6)and(x<81-dim)and(y<25-dim) then dim:=dim+1;
           if (c='-')and(dim>1) then dim:=dim-1;
           if c='p' then penna:=penna+1;
           if penna=3 then penna:=0;
           for i:=30 to 45 do
               begin
                    gotoxy(i,25);
                    write('-');
               end;
           gotoxy(20,25);
           write('cursore: ');
           gotoxy(29,25);
           if penna=0 then write('neutro');
           if penna=1 then write('pennarello - ',dim);
           if penna=2 then write('gomma - ',dim);
           gotoxy(40,1); gotoxy(1,2);
           gotoxy(x,y);
           c:=readkey;
           until (c='a')or(c='w')or(c='s')or(c='d')or(c='q');
        if c='a' then x:=x-1;
        if c='s' then y:=y+1;
        if c='d' then x:=x+1;
        if c='w' then y:=y-1;
        if x=0 then x:=80;
        if x=81 then x:=1;
        if y=0 then y:=24;
        if y=25 then y:=1;
        gotoxy(x,y);
        textcolor(letter_color);
        if penna=1 then textbackground(writing_color);
        if penna=2 then textbackground(background_color);
        if penna<>0 then
           for i:=y to y-1+dim do
               for k:=x to x-1+dim do
                  begin
                    if i<25 then
                      begin
                       gotoxy(k,i);
                       if penna=1 then
                        begin
                             write(letter);
                             pixel[k][i][1]:=writing_color;
                             pixel[k][i][2]:=letter_color;
                             pixletter[k][i]:=letter;
                        end
                        else
                        begin
                             write(' ');
                             pixel[k][i][1]:=background_color;
                             pixel[k][i][2]:=letter_color;
                             pixletter[k][i]:=' ';
                        end;
                      end;
                  end;
     until (c='q');
     rewrite(bitmap);
     for j:= 1 to 2 do
       for i:=1 to 24 do
         for k:=1 to 80 do writeln(bitmap,pixel[k][i][j]);
     for i:=1 to 24 do
       for k:=1 to 80 do writeln(bitmap,pixletter[k][i]);
     writeln(bitmap,background_color);
     close(bitmap);
end.

